extends GutTest

# Tests for the Atlas — the whole influence graph as a star chart.
#
# Two halves. The BAKED LAYOUT (data/atlas_layout.tres, generated by
# tools/bake_atlas.py) has to describe the catalog truthfully and place no two
# stars on top of each other, since the packing is the whole point. The VIEW has
# to build headless, frame itself, pick stars in screen space, and draw the run's
# route once a run is under way.

const ATLAS := preload("res://scripts/ui/AtlasView.gd")
const OVERWORLD := preload("res://scenes/redesign2/Overworld2.tscn")

var _layout: AtlasLayout

func before_all() -> void:
	_layout = ATLAS.load_layout()

func after_each() -> void:
	GameState.reset_run()
	GameLoop2.reset()

func _open() -> AtlasView:
	var view: AtlasView = ATLAS.new()
	add_child_autofree(view)
	return view

# ---------------------------------------------------------------------------
# The baked layout
# ---------------------------------------------------------------------------

func test_layout_resource_exists() -> void:
	assert_not_null(_layout, "data/atlas_layout.tres is baked (run tools/bake_atlas.py)")

func test_layout_covers_every_game() -> void:
	if _layout == null:
		return
	var catalog: int = Data.all_games().size()
	assert_eq(_layout.star_count(), catalog, "every game in the catalog has a star")
	for g in Data.all_games():
		assert_gte(_layout.index_of(g.id), 0, "%s has a position" % g.id)

func test_parallel_arrays_are_the_same_length() -> void:
	if _layout == null:
		return
	var n: int = _layout.star_count()
	assert_eq(_layout.xs.size(), n, "one x per star")
	assert_eq(_layout.ys.size(), n, "one y per star")
	assert_eq(_layout.region.size(), n, "one region per star")
	assert_eq(_layout.hops.size(), n, "one hop count per star")

func test_edges_are_pairs_of_real_stars() -> void:
	if _layout == null:
		return
	assert_eq(_layout.edges.size() % 2, 0, "the edge list is flat pairs")
	assert_gt(_layout.edge_count(), 0, "the sky has links in it")
	var n: int = _layout.star_count()
	for i in range(_layout.edges.size()):
		var idx: int = _layout.edges[i]
		assert_true(idx >= 0 and idx < n, "edge endpoint %d is a real star" % idx)

# The packing exists to guarantee this: two stars drawn at their baked radii
# never overlap. If this fails the layout is wrong, not the renderer.
func test_no_two_stars_overlap() -> void:
	if _layout == null:
		return
	var n: int = _layout.star_count()
	var cell: float = 48.0
	var grid: Dictionary = {}
	for i in range(n):
		var key: Vector2i = Vector2i(int(floor(_layout.xs[i] / cell)), int(floor(_layout.ys[i] / cell)))
		if not grid.has(key):
			grid[key] = []
		(grid[key] as Array).append(i)
	var overlaps: int = 0
	for i in range(n):
		var base: Vector2i = Vector2i(int(floor(_layout.xs[i] / cell)), int(floor(_layout.ys[i] / cell)))
		for ax in range(-1, 2):
			for ay in range(-1, 2):
				for j in grid.get(base + Vector2i(ax, ay), []):
					if int(j) <= i:
						continue
					var need: float = AtlasLayout.star_radius(_layout.degree_of(i)) \
						+ AtlasLayout.star_radius(_layout.degree_of(int(j)))
					if _layout.position_of(i).distance_to(_layout.position_of(int(j))) < need - 0.001:
						overlaps += 1
	assert_eq(overlaps, 0, "no two stars overlap at their drawn radii")

func test_capitals_are_the_highest_degree_games() -> void:
	if _layout == null:
		return
	assert_gt(_layout.capitals.size(), 0, "the sky has capitals")
	var cap_degree: int = _layout.degree_of(_layout.capitals[0])
	for i in range(_layout.star_count()):
		assert_lte(_layout.degree_of(i), cap_degree,
			"no star out-connects the first capital")

func test_every_star_is_in_a_region_or_drifting() -> void:
	if _layout == null:
		return
	for i in range(_layout.star_count()):
		var r: int = _layout.region[i]
		assert_true(r == -1 or (r >= 0 and r < _layout.capitals.size()),
			"star %d has a valid region" % i)
		# A star in a region knows how far it is from its capital; a drifting one doesn't.
		if r >= 0:
			assert_gte(_layout.hops[i], 0, "a placed star has a hop count")

func test_capitals_sit_at_hop_zero_of_their_own_region() -> void:
	if _layout == null:
		return
	for ci in range(_layout.capitals.size()):
		var cap: int = _layout.capitals[ci]
		assert_eq(_layout.region[cap], ci, "capital %d owns its own region" % ci)
		assert_eq(_layout.hops[cap], 0, "a capital is zero hops from itself")

func test_bounds_contain_every_star() -> void:
	if _layout == null:
		return
	for i in range(_layout.star_count()):
		assert_true(_layout.bounds.has_point(_layout.position_of(i)),
			"star %d is inside the baked bounds" % i)

# ---------------------------------------------------------------------------
# The view
# ---------------------------------------------------------------------------

func test_view_builds_headless() -> void:
	var view := _open()
	assert_true(view.has_layout(), "the view loaded the baked layout")
	assert_gt(view.zoom_ratio(), 0.0, "the view framed itself")

func test_neighbors_match_the_baked_edges() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var counted: int = 0
	for i in range(view.layout.star_count()):
		counted += view.neighbors_of(i).size()
	assert_eq(counted, view.layout.edge_count() * 2,
		"each edge shows up once from each end")

func test_neighbors_are_symmetric() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var a: int = view.layout.capitals[0]
	for n in view.neighbors_of(a):
		assert_true(view.neighbors_of(int(n)).has(a),
			"the graph the atlas draws is undirected")

func test_selecting_a_star_lights_its_links() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var cap: int = view.layout.capitals[0]
	view.select(cap)
	assert_eq(view.selected_index(), cap, "the star is selected")
	assert_eq(view._near.size(), view.neighbors_of(cap).size() + 1,
		"the halo is the star plus its neighbours")
	view.select(-1)
	assert_eq(view.selected_index(), -1, "selection clears")
	assert_eq(view._near.size(), 0, "the halo clears with it")

# Screen-space picking is what keeps a 1px dot clickable at overview zoom.
func test_picking_finds_the_star_under_the_cursor() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var target: int = view.layout.capitals[0]
	var at: Vector2 = view.to_screen(view.layout.position_of(target))
	assert_eq(view.pick(at), target, "clicking a star picks it")

func test_picking_empty_sky_returns_nothing() -> void:
	var view := _open()
	if not view.has_layout():
		return
	# Far outside the bounds, so nothing is within the screen-space tolerance.
	var far: Vector2 = view.to_screen(view.layout.bounds.end + Vector2(6000, 6000))
	assert_eq(view.pick(far), -1, "empty sky picks nothing")

func test_focus_game_centres_and_selects() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var id: StringName = view.layout.id_at(view.layout.capitals[0])
	assert_true(view.focus_game(id), "focusing a real game succeeds")
	assert_eq(view.selected_index(), view.layout.capitals[0], "focusing selects it")

func test_focus_unknown_game_is_refused() -> void:
	var view := _open()
	if not view.has_layout():
		return
	assert_false(view.focus_game(&"not_a_real_game"), "an unknown id is refused")

func test_zoom_is_clamped() -> void:
	var view := _open()
	if not view.has_layout():
		return
	for _i in range(60):
		view.zoom_by(2.0, Vector2(400, 300))
	assert_lte(view.zoom_ratio(), AtlasView.ZOOM_MAX + 0.001, "zoom stops at the ceiling")
	for _i in range(60):
		view.zoom_by(0.5, Vector2(400, 300))
	assert_gte(view.zoom_ratio(), AtlasView.ZOOM_MIN - 0.001, "zoom stops at the floor")

func test_hulls_cover_every_region() -> void:
	var view := _open()
	if not view.has_layout():
		return
	assert_eq(view.hulls().size(), view.layout.capitals.size(),
		"every constellation has a hull")
	for hull in view.hulls():
		assert_gt(float(hull["radius"]), 0.0, "a hull has size")

# ---------------------------------------------------------------------------
# Cover art — stars become their box art when you zoom in far enough
# ---------------------------------------------------------------------------

# A cover is inscribed in the circle the packing reserved for its star, so its
# half-diagonal is exactly that radius. This is what lets art replace the dots
# with no second layout pass.
func test_cover_is_inscribed_in_its_reserved_circle() -> void:
	for aspect in [0.5, 1.0, 4.0 / 3.0, 1.5, 2.0]:
		for radius in [2.45, 6.0, 12.1]:
			var s: Vector2 = AtlasView.cover_size(radius, aspect)
			assert_almost_eq(s.length() * 0.5, radius, 0.001,
				"a %0.2f-aspect cover at r=%0.2f fills its circle exactly" % [aspect, radius])
			assert_almost_eq(s.y / s.x, aspect, 0.001, "the cover keeps its aspect ratio")

func test_cover_size_is_degenerate_when_it_should_be() -> void:
	assert_eq(AtlasView.cover_size(0.0, 1.0), Vector2.ZERO, "no radius, no cover")
	assert_eq(AtlasView.cover_size(5.0, 0.0), Vector2.ZERO, "no aspect, no cover")

# The real proof: over the actual catalog, no two covers can overlap, because no
# two reserved circles do.
func test_no_two_covers_can_overlap() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var lay: AtlasLayout = view.layout
	var checked: int = 0
	var overlaps: int = 0
	var cell: float = 48.0
	var grid: Dictionary = {}
	for i in range(lay.star_count()):
		var key := Vector2i(int(floor(lay.xs[i] / cell)), int(floor(lay.ys[i] / cell)))
		if not grid.has(key):
			grid[key] = []
		(grid[key] as Array).append(i)
	for i in range(lay.star_count()):
		var tex_a: Texture2D = view.cover_texture(i)
		if tex_a == null:
			continue
		var box_a := _world_cover_rect(view, lay, i, tex_a)
		var base := Vector2i(int(floor(lay.xs[i] / cell)), int(floor(lay.ys[i] / cell)))
		for ax in range(-1, 2):
			for ay in range(-1, 2):
				for j in grid.get(base + Vector2i(ax, ay), []):
					if int(j) <= i:
						continue
					var tex_b: Texture2D = view.cover_texture(int(j))
					if tex_b == null:
						continue
					checked += 1
					if box_a.intersects(_world_cover_rect(view, lay, int(j), tex_b)):
						overlaps += 1
	assert_gt(checked, 0, "there are neighbouring covers to check")
	assert_eq(overlaps, 0, "no two cover images overlap anywhere in the sky")

func _world_cover_rect(view: AtlasView, lay: AtlasLayout, i: int, tex: Texture2D) -> Rect2:
	var aspect: float = float(tex.get_height()) / float(tex.get_width())
	var reserved: float = AtlasLayout.star_radius(lay.degree_of(i))
	var s: Vector2 = AtlasView.cover_size(reserved, aspect)
	return Rect2(lay.position_of(i) - s * 0.5, s)

func test_most_games_have_cover_art() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var with_art: int = 0
	for i in range(view.layout.star_count()):
		if view.cover_texture(i) != null:
			with_art += 1
	assert_gt(with_art, int(view.layout.star_count() * 0.9),
		"the great majority of stars have box art to show")

func test_drawn_half_height_tracks_what_is_actually_drawn() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var i: int = view.layout.capitals[0]
	assert_gt(view.drawn_half_height(i), 0.0, "something is always drawn for a star")

# The point of a per-star threshold: the best-connected games become art at a
# lower zoom than the fringe does, so the map fills in from its hubs outward.
func test_well_connected_games_become_art_sooner() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var hub: int = view.layout.capitals[0]
	var leaf: int = -1
	for i in range(view.layout.star_count()):
		if view.layout.degree_of(i) == 1 and view.cover_texture(i) != null:
			leaf = i
			break
	if leaf < 0 or view.cover_texture(hub) == null:
		return
	# Zoom up from the overview one step at a time and record which flips first.
	var hub_at: float = -1.0
	var leaf_at: float = -1.0
	view.frame_all()
	for _step in range(120):
		if hub_at < 0.0 and view.shows_cover(hub):
			hub_at = view.zoom_ratio()
		if leaf_at < 0.0 and view.shows_cover(leaf):
			leaf_at = view.zoom_ratio()
		if hub_at > 0.0 and leaf_at > 0.0:
			break
		view.zoom_by(1.1, Vector2(400, 300))
	assert_gt(hub_at, 0.0, "the hub becomes art at some zoom")
	assert_gt(leaf_at, 0.0, "the dead end becomes art at some zoom")
	assert_lt(hub_at, leaf_at,
		"a 124-connection hub shows its cover before a 1-connection game does")

func test_nothing_shows_art_at_the_overview() -> void:
	var view := _open()
	if not view.has_layout():
		return
	view.frame_all()
	assert_eq(view.cover_count(), 0, "the whole-sky overview is dots, not stamps")

func test_everything_with_art_shows_it_when_zoomed_right_in() -> void:
	var view := _open()
	if not view.has_layout():
		return
	for _step in range(80):
		view.zoom_by(1.3, Vector2(400, 300))
	var with_art: int = 0
	for i in range(view.layout.star_count()):
		if view.cover_texture(i) != null:
			with_art += 1
	assert_eq(view.cover_count(), with_art,
		"at maximum zoom every game that has art is showing it")

# ---------------------------------------------------------------------------
# The run trail — the corridor drawn over the sky
# ---------------------------------------------------------------------------

func test_no_trail_without_a_run() -> void:
	var view := _open()
	assert_eq(view.trail_segment_count(), 0, "no run, no trail")

func test_trail_follows_the_run() -> void:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	var view := _open()
	if not view.has_layout():
		return
	assert_gt(view.trail_segment_count(), 0, "a run in progress draws a trail")
	# Every segment is a real edge between two real stars.
	for seg in view._trail:
		var a: int = int(seg[0])
		var b: int = int(seg[1])
		assert_true(a >= 0 and a < view.layout.star_count(), "trail start is a real star")
		assert_true(b >= 0 and b < view.layout.star_count(), "trail end is a real star")
		assert_true(view.neighbors_of(a).has(b), "a trail segment is a real connection")

func test_framing_the_trail_keeps_the_route_on_screen() -> void:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	var view := _open()
	if not view.has_layout() or view.trail_segment_count() == 0:
		return
	view.frame_trail()
	# The current game and the amulet both sit inside the framed view.
	var current: int = view.layout.index_of(GameState.current_game_id)
	var amulet: int = view.layout.index_of(GameState.amulet_game_id)
	var canvas := Rect2(Vector2.ZERO, view._canvas_size())
	for idx in [current, amulet]:
		if idx >= 0:
			assert_true(canvas.grow(4.0).has_point(view.to_screen(view.layout.position_of(idx))),
				"the route's endpoints are framed")

# ---------------------------------------------------------------------------
# Filtered skies — one layout per Settings.game_filter
# ---------------------------------------------------------------------------

# The Atlas has to draw the graph the run actually travels. With an owned-only
# filter a route through an unowned game doesn't exist, so the sky is laid out
# over the owned subgraph rather than being the full map with stars hidden.
func test_owned_sky_holds_only_owned_games() -> void:
	var owned: AtlasLayout = ATLAS.load_layout(Settings.GameFilter.OWNED)
	assert_not_null(owned, "data/atlas_layout_owned.tres is baked")
	if owned == null:
		return
	assert_eq(owned.source_filter, "owned", "the sky knows which filter it is")
	for i in range(owned.star_count()):
		var game: GameData = Data.get_game(owned.id_at(i))
		assert_not_null(game, "every star is a real game")
		if game != null:
			assert_true(game.owned, "%s is owned" % game.id)

func test_owned_sky_is_smaller_than_the_full_one() -> void:
	var owned: AtlasLayout = ATLAS.load_layout(Settings.GameFilter.OWNED)
	if owned == null or _layout == null:
		return
	assert_lt(owned.star_count(), _layout.star_count(),
		"the owned sky is a subset of the whole catalog")
	assert_gt(owned.star_count(), 0, "and it isn't empty")

# It's laid out from scratch, not cropped — so a game's position differs between
# the two skies, and the owned sky picks its own capitals.
func test_owned_sky_is_laid_out_independently() -> void:
	var owned: AtlasLayout = ATLAS.load_layout(Settings.GameFilter.OWNED)
	if owned == null or _layout == null:
		return
	assert_gt(owned.capitals.size(), 0, "the owned sky has its own capitals")
	var moved: int = 0
	for i in range(owned.star_count()):
		var j: int = _layout.index_of(owned.id_at(i))
		if j >= 0 and owned.position_of(i).distance_to(_layout.position_of(j)) > 0.5:
			moved += 1
	assert_gt(moved, owned.star_count() / 2,
		"most stars sit somewhere else than they do on the full map")

func test_owned_sky_has_no_overlapping_stars() -> void:
	var owned: AtlasLayout = ATLAS.load_layout(Settings.GameFilter.OWNED)
	if owned == null:
		return
	var overlaps: int = 0
	for i in range(owned.star_count()):
		for j in range(i + 1, owned.star_count()):
			var need: float = AtlasLayout.star_radius(owned.degree_of(i)) \
				+ AtlasLayout.star_radius(owned.degree_of(j))
			if owned.position_of(i).distance_to(owned.position_of(j)) < need - 0.001:
				overlaps += 1
	assert_eq(overlaps, 0, "the owned sky packs cleanly too")

# Every edge in a filtered sky must have both ends inside that filter — this is
# what stops the map drawing a route the run can't walk.
func test_filtered_sky_edges_stay_inside_the_filter() -> void:
	var owned: AtlasLayout = ATLAS.load_layout(Settings.GameFilter.OWNED)
	if owned == null:
		return
	var e: int = 0
	while e + 1 < owned.edges.size():
		for idx in [owned.edges[e], owned.edges[e + 1]]:
			var game: GameData = Data.get_game(owned.id_at(int(idx)))
			assert_true(game != null and game.owned, "both ends of a link are owned")
		e += 2

func test_the_view_opens_the_sky_matching_the_active_filter() -> void:
	var previous: int = Settings.game_filter
	Settings.game_filter = Settings.GameFilter.OWNED
	var view := _open()
	if view.has_layout():
		assert_eq(view.layout.source_filter, "owned",
			"opening the Atlas under an owned-only filter shows the owned sky")
	Settings.game_filter = previous

func test_an_unbaked_filter_falls_back_to_the_full_sky() -> void:
	# 99 is not a real GameFilter value, so nothing is baked for it.
	var fallback: AtlasLayout = ATLAS.load_layout(99)
	assert_not_null(fallback, "an unknown filter still gets a map")
	if fallback != null:
		assert_eq(fallback.source_filter, "all", "and it's the full one")

# ---------------------------------------------------------------------------
# Line hierarchy — background links, a clicked game's connections, the route
# ---------------------------------------------------------------------------

# Clicking a game must light up ALL of its connections, not a sample of them.
func test_clicking_a_game_lights_every_one_of_its_connections() -> void:
	var view := _open()
	if not view.has_layout():
		return
	for target in [view.layout.capitals[0], view.layout.capitals[3]]:
		view.select(target)
		var lit: int = 0
		var e: int = 0
		while e + 1 < view.layout.edges.size():
			var a: int = view.layout.edges[e]
			var b: int = view.layout.edges[e + 1]
			e += 2
			if a == target or b == target:
				lit += 1
		assert_eq(lit, view.neighbors_of(target).size(),
			"%s lights all %d of its links" % [view.layout.id_at(target), lit])
		assert_eq(view._near.size(), lit + 1,
			"and every game they reach is in the halo, plus the game itself")

# A dead end has exactly one connection and it still highlights.
func test_a_one_connection_game_still_highlights() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var leaf: int = -1
	for i in range(view.layout.star_count()):
		if view.layout.degree_of(i) == 1:
			leaf = i
			break
	if leaf < 0:
		return
	view.select(leaf)
	assert_eq(view._near.size(), 2, "a dead end highlights itself and its one neighbour")

func test_selection_survives_zooming_out_past_the_link_threshold() -> void:
	var view := _open()
	if not view.has_layout():
		return
	view.select(view.layout.capitals[0])
	for _i in range(30):
		view.zoom_by(0.6, Vector2(400, 300))
	assert_lt(view.zoom_ratio(), AtlasView.ZOOM_LINKS,
		"we are zoomed out past where background links stop drawing")
	assert_eq(view.selected_index(), view.layout.capitals[0],
		"the clicked game stays selected, so its connections still draw")

# The route is a distinct treatment, not a brighter background link — the three
# line colours must stay tellable apart.
func test_route_selection_and_background_lines_are_distinct() -> void:
	var route: Color = AtlasView.COL_TRAIL
	var picked: Color = AtlasView.COL_SELECTED_EDGE
	var backdrop: Color = AtlasView.COL_EDGE
	assert_gt(_separation(route, picked), 0.25, "the route can't be mistaken for a selection")
	assert_gt(_separation(route, backdrop), 0.25, "or for a background link")
	assert_gt(picked.a, backdrop.a, "a clicked game's links are stronger than the backdrop")

func _separation(a: Color, b: Color) -> float:
	return absf(a.r - b.r) + absf(a.g - b.g) + absf(a.b - b.b)

func test_walked_and_remaining_route_are_told_apart() -> void:
	assert_gt(_separation(AtlasView.COL_TRAIL, AtlasView.COL_HISTORY), 0.4,
		"the road behind you doesn't look like the road ahead")

# The route drawn on the atlas is exactly the DAG the run minimap draws.
func test_route_matches_the_run_minimap_exactly() -> void:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	var view := _open()
	if not view.has_layout() or view.trail_segment_count() == 0:
		return
	var dag: Dictionary = RunGraph.shortest_path_dag(
		GameState.current_game_id, GameState.amulet_game_id)
	var expected: Dictionary = {}
	for edge in dag.get("edges", []):
		expected["%s>%s" % [edge["from"], edge["to"]]] = true
	assert_eq(view.trail_segment_count(), expected.size(),
		"the atlas route has one segment per minimap edge")
	for seg in view._trail:
		var key: String = "%s>%s" % [view.layout.id_at(int(seg[0])), view.layout.id_at(int(seg[1]))]
		assert_true(expected.has(key), "%s is an edge the minimap also draws" % key)

# Selecting a game must not hide the route — it's the one thing that stays.
func test_the_route_survives_selecting_something_else() -> void:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	var view := _open()
	if not view.has_layout():
		return
	var before: int = view.trail_segment_count()
	if before == 0:
		return
	view.select(view.layout.capitals[0])
	assert_eq(view.trail_segment_count(), before,
		"clicking a game elsewhere leaves the route to the Amulet drawn")

# ---------------------------------------------------------------------------
# Route arrowheads — which way the road runs
# ---------------------------------------------------------------------------

func test_arrows_clear_the_stars_at_both_ends() -> void:
	var pad_a: float = 30.0
	var pad_b: float = 18.0
	var size: float = 14.0
	var offsets: PackedFloat32Array = AtlasView.route_arrow_offsets(400.0, pad_a, pad_b, size)
	assert_gt(offsets.size(), 0, "a long segment carries arrows")
	for t in offsets:
		assert_gte(t, pad_a, "no arrow sits on the star it leaves")
		assert_lte(t, 400.0 - pad_b, "and none sits on the star it reaches")

func test_a_long_segment_gets_several_arrows() -> void:
	var few: PackedFloat32Array = AtlasView.route_arrow_offsets(160.0, 6.0, 6.0, 12.0)
	var many: PackedFloat32Array = AtlasView.route_arrow_offsets(900.0, 6.0, 6.0, 12.0)
	assert_gt(many.size(), few.size(),
		"a route crossing the sky gets more arrows than a short hop")
	assert_gte(few.size(), 1, "even a modest segment gets one")

func test_arrows_are_evenly_spaced() -> void:
	var offsets: PackedFloat32Array = AtlasView.route_arrow_offsets(900.0, 10.0, 10.0, 12.0)
	if offsets.size() < 3:
		return
	var first_gap: float = offsets[1] - offsets[0]
	for i in range(2, offsets.size()):
		assert_almost_eq(offsets[i] - offsets[i - 1], first_gap, 0.01,
			"the spacing between arrowheads is uniform")

# A plain line beats a smudge: too short to hold an arrowhead means no arrowhead.
func test_a_short_segment_gets_no_arrow() -> void:
	assert_eq(AtlasView.route_arrow_offsets(20.0, 8.0, 8.0, 14.0).size(), 0,
		"a segment swallowed by its endpoints carries nothing")
	assert_eq(AtlasView.route_arrow_offsets(0.0, 0.0, 0.0, 12.0).size(), 0,
		"a zero-length segment carries nothing")
	assert_eq(AtlasView.route_arrow_offsets(400.0, 0.0, 0.0, 0.0).size(), 0,
		"a zero-size arrow is never placed")

# Arrows have to point from the game nearer you toward the game nearer the
# Amulet, or they'd send the player the wrong way.
func test_route_segments_run_toward_the_amulet() -> void:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	var view := _open()
	if not view.has_layout() or view.trail_segment_count() == 0:
		return
	var to_amulet: Dictionary = RunGraph.bfs_distances(GameState.amulet_game_id)
	for seg in view._trail:
		var from_id: StringName = view.layout.id_at(int(seg[0]))
		var to_id: StringName = view.layout.id_at(int(seg[1]))
		assert_true(to_amulet.has(from_id) and to_amulet.has(to_id),
			"both ends of a route segment can reach the Amulet")
		assert_eq(int(to_amulet[to_id]), int(to_amulet[from_id]) - 1,
			"every arrow points one step closer to the Amulet")

# ---------------------------------------------------------------------------
# The path taken — where the player has actually been this run
# ---------------------------------------------------------------------------

# This is a genuinely different road from the route ahead: shortest_path_dag is
# recomputed from where the player stands TO the Amulet, so it never contains a
# game already behind them.
func test_no_path_taken_before_the_run_moves() -> void:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	var view := _open()
	assert_eq(view.history_segment_count(), 0,
		"standing on the starting game, nothing has been walked yet")

func test_path_taken_grows_as_the_player_moves() -> void:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	var start_id: StringName = GameState.current_game_id
	var next: Array = RunGraph.neighbors(start_id)
	if next.is_empty():
		return
	GameState.set_current_game(next[0])
	var view := _open()
	if not view.has_layout():
		return
	assert_eq(view.history_segment_count(), 1, "one hop walked, one segment drawn")
	var seg: Array = view._history[0]
	assert_eq(view.layout.id_at(int(seg[0])), start_id, "it starts where the run started")
	assert_eq(view.layout.id_at(int(seg[1])), StringName(next[0]), "and ends where the player is")
	assert_false(bool(seg[2]), "a normal move follows a real connection")

func test_path_taken_follows_the_order_the_games_were_visited() -> void:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	# Walk three real connections.
	for _hop in range(3):
		var options: Array = RunGraph.neighbors(GameState.current_game_id)
		var moved: bool = false
		for candidate in options:
			if not GameState.visited_games.has(candidate) and candidate != GameState.current_game_id:
				GameState.set_current_game(candidate)
				moved = true
				break
		if not moved:
			break
	var view := _open()
	if not view.has_layout() or view.history_segment_count() < 2:
		return
	var walked: Array = GameState.visited_games.duplicate()
	walked.append(GameState.current_game_id)
	assert_eq(view.history_segment_count(), walked.size() - 1,
		"one segment per hop actually taken")
	for i in range(view.history_segment_count()):
		var seg: Array = view._history[i]
		assert_eq(view.layout.id_at(int(seg[0])), StringName(walked[i]),
			"segment %d leaves the right game" % i)
		assert_eq(view.layout.id_at(int(seg[1])), StringName(walked[i + 1]),
			"segment %d arrives at the next one" % i)

# Teleport and Winged Boots move the player without traversing a link, so that
# hop is flagged and drawn dashed rather than passed off as a road.
func test_a_hop_with_no_connection_is_flagged_as_a_jump() -> void:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	var start_id: StringName = GameState.current_game_id
	# Find a game that is definitely NOT connected to the start.
	var stranger: StringName = &""
	var linked: Array = RunGraph.neighbors(start_id)
	for g in Data.all_games():
		if g.id != start_id and not linked.has(g.id):
			stranger = g.id
			break
	if stranger == &"":
		return
	GameState.set_current_game(stranger)
	var view := _open()
	if not view.has_layout() or view.history_segment_count() == 0:
		return
	assert_true(bool(view._history[0][2]),
		"a move with no link between the two games reads as a jump")

func test_path_taken_and_route_ahead_are_separate_roads() -> void:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	var next: Array = RunGraph.neighbors(GameState.current_game_id)
	if next.is_empty():
		return
	GameState.set_current_game(next[0])
	var view := _open()
	if not view.has_layout():
		return
	assert_gt(view.history_segment_count(), 0, "there is a road behind")
	# No segment appears on both roads: the DAG starts where the player stands.
	var behind: Dictionary = {}
	for seg in view._history:
		behind["%d>%d" % [int(seg[0]), int(seg[1])]] = true
	for seg in view._trail:
		assert_false(behind.has("%d>%d" % [int(seg[0]), int(seg[1])]),
			"the road ahead never repeats a stretch already walked")

func test_my_run_framing_covers_both_roads() -> void:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	var next: Array = RunGraph.neighbors(GameState.current_game_id)
	if next.is_empty():
		return
	var start_id: StringName = GameState.current_game_id
	GameState.set_current_game(next[0])
	var view := _open()
	if not view.has_layout() or view.history_segment_count() == 0:
		return
	view.frame_trail()
	var canvas := Rect2(Vector2.ZERO, view._canvas_size()).grow(4.0)
	var origin: int = view.layout.index_of(start_id)
	if origin >= 0:
		assert_true(canvas.has_point(view.to_screen(view.layout.position_of(origin))),
			"framing the run includes where it began, not just the road ahead")

# ---------------------------------------------------------------------------
# Staleness — the baked skies are build artefacts, and they can go out of date
# ---------------------------------------------------------------------------
#
# data/atlas_layout*.tres are generated by tools/bake_atlas.py and committed. If
# the catalog changes and the bake isn't re-run — an import that half-failed, a
# hand-edited .tres, a merge that took one side — the Atlas keeps drawing the old
# sky and nothing complains. These tests make that loud.
#
# If one fails, the fix is almost always:  python3 tools/bake_atlas.py --all-filters

# The undirected edge set the catalog describes right now, as "a|b" keys with the
# pair sorted, so it can be compared to a bake regardless of which way round each
# edge was stored.
func _catalog_edge_keys(only_owned: bool = false, only_downloaded: bool = false) -> Dictionary:
	var present: Dictionary = {}
	for g in Data.all_games():
		if only_owned and not g.owned:
			continue
		if only_downloaded and g.file_location.strip_edges() == "":
			continue
		present[g.id] = true
	var keys: Dictionary = {}
	for g in Data.all_games():
		if not present.has(g.id):
			continue
		for other in g.games_influenced:
			if not present.has(other) or other == g.id:
				continue
			var a: String = String(g.id)
			var b: String = String(other)
			keys["%s|%s" % ([a, b] if a < b else [b, a])] = true
	return keys

func _baked_edge_keys(lay: AtlasLayout) -> Dictionary:
	var keys: Dictionary = {}
	var e: int = 0
	while e + 1 < lay.edges.size():
		var a: String = String(lay.id_at(lay.edges[e]))
		var b: String = String(lay.id_at(lay.edges[e + 1]))
		keys["%s|%s" % ([a, b] if a < b else [b, a])] = true
		e += 2
	return keys

# Star count alone doesn't catch a changed CONNECTION — add a link between two
# existing games and the star count is identical while the map is wrong.
func test_baked_sky_matches_the_catalogs_connections() -> void:
	if _layout == null:
		return
	var want: Dictionary = _catalog_edge_keys()
	var have: Dictionary = _baked_edge_keys(_layout)
	var missing: Array = []
	for k in want:
		if not have.has(k):
			missing.append(k)
	var extra: Array = []
	for k in have:
		if not want.has(k):
			extra.append(k)
	assert_eq(missing.size(), 0,
		"connections in the catalog but not in the bake (re-run tools/bake_atlas.py): %s"
		% str(missing.slice(0, 5)))
	assert_eq(extra.size(), 0,
		"connections in the bake but no longer in the catalog: %s" % str(extra.slice(0, 5)))

func test_baked_sky_matches_the_catalogs_games() -> void:
	if _layout == null:
		return
	var baked: Dictionary = {}
	for i in range(_layout.star_count()):
		baked[_layout.id_at(i)] = true
	for g in Data.all_games():
		assert_true(baked.has(g.id), "%s is in the catalog but has no star" % g.id)
	assert_eq(baked.size(), Data.all_games().size(), "and the bake holds nothing extra")

func test_filtered_skies_are_baked_from_the_same_catalog() -> void:
	for spec in [[Settings.GameFilter.OWNED, true, false], [Settings.GameFilter.DOWNLOADED, false, true]]:
		var lay: AtlasLayout = ATLAS.load_layout(int(spec[0]))
		if lay == null or lay.source_filter == "all":
			continue
		var want: Dictionary = _catalog_edge_keys(bool(spec[1]), bool(spec[2]))
		var have: Dictionary = _baked_edge_keys(lay)
		assert_eq(have.size(), want.size(),
			"the '%s' sky has as many links as that filter's catalog does" % lay.source_filter)
		for k in want:
			assert_true(have.has(k), "'%s' sky is missing %s" % [lay.source_filter, k])

# Degrees are read off the baked edge list, so a stale bake would also mis-size
# every star. Check them against the catalog directly.
func test_star_sizes_match_the_catalogs_connection_counts() -> void:
	if _layout == null:
		return
	var degree: Dictionary = {}
	for g in Data.all_games():
		degree[g.id] = 0
	for g in Data.all_games():
		for other in g.games_influenced:
			if degree.has(other) and other != g.id:
				degree[g.id] = int(degree[g.id]) + 1
				degree[other] = int(degree[other]) + 1
	for i in range(_layout.star_count()):
		assert_eq(_layout.degree_of(i), int(degree.get(_layout.id_at(i), -1)),
			"%s is drawn at the size its connection count says" % _layout.id_at(i))

# ---------------------------------------------------------------------------
# Connections — clicking a link, and the evidence behind it
# ---------------------------------------------------------------------------

func test_connection_evidence_is_imported() -> void:
	var with_source: int = 0
	var dev_series: int = 0
	var misaligned: int = 0
	for g in Data.all_games():
		# The evidence arrays are index-aligned with games_influenced; a short one
		# would silently attribute a source to the wrong connection.
		if g.influence_sources.size() != g.games_influenced.size() \
				or g.influence_relations.size() != g.games_influenced.size():
			misaligned += 1
		for src in g.influence_sources:
			if String(src).strip_edges() != "":
				with_source += 1
		for rel in g.influence_relations:
			if String(rel).strip_edges() != "":
				dev_series += 1
	assert_eq(misaligned, 0, "every game's evidence lines up with its connections")
	assert_gt(with_source, 500, "most connections carry a source (the sheet has ~880)")
	assert_gt(dev_series, 50, "the sequel / same-devs flag came through too")

func test_influence_is_described_in_the_authored_direction() -> void:
	var older: GameData = Data.get_game(&"rogue")
	var newer: GameData = Data.get_game(&"brogue")
	if older == null or newer == null:
		return
	# Asked either way round, the answer names the influencer as the source.
	for pair in [[older, newer], [newer, older]]:
		var d: Dictionary = GameData.describe_influence(pair[0], pair[1])
		assert_false(d.is_empty(), "Rogue and Brogue are connected")
		assert_eq((d["from"] as GameData).id, older.id, "Rogue is the influencer")
		assert_eq((d["to"] as GameData).id, newer.id, "Brogue is the influenced")

func test_unconnected_games_describe_nothing() -> void:
	var a: GameData = Data.get_game(&"rogue")
	var b: GameData = Data.get_game(&"balatro")
	if a == null or b == null:
		return
	assert_true(GameData.describe_influence(a, b).is_empty(),
		"two games with no link between them have nothing to describe")

func test_only_real_urls_are_offered_as_openable() -> void:
	assert_true(GameData.is_openable_source("https://roguebasin.com/index.php/Brogue"))
	assert_true(GameData.is_openable_source("  http://example.com/x  "))
	assert_false(GameData.is_openable_source("check folder"))
	assert_false(GameData.is_openable_source("game credits"))
	assert_false(GameData.is_openable_source(""))

func test_clicking_a_link_picks_it() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var e: int = 0
	var a: int = view.layout.edges[0]
	var b: int = view.layout.edges[1]
	# The midpoint of a link is unambiguously on that link.
	var mid: Vector2 = (view.to_screen(view.layout.position_of(a))
		+ view.to_screen(view.layout.position_of(b))) * 0.5
	assert_eq(view.pick_edge(mid), e, "clicking the middle of a link picks it")

func test_empty_sky_picks_no_link() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var far: Vector2 = view.to_screen(view.layout.bounds.end + Vector2(9000, 9000))
	assert_eq(view.pick_edge(far), -1, "empty sky has no link under it")

func test_a_link_reports_both_games_and_its_evidence() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var found: int = -1
	for e in range(view.layout.edge_count()):
		if String(view.edge_details(e).get("source", "")) != "":
			found = e
			break
	assert_gte(found, 0, "some link on the map carries a source")
	var d: Dictionary = view.edge_details(found)
	assert_true(d["from"] is GameData and d["to"] is GameData, "both games are named")
	assert_ne((d["from"] as GameData).id, (d["to"] as GameData).id, "and they're different games")
	assert_ne(String(d["source"]), "", "with the evidence behind the claim")

func test_selecting_a_link_and_a_game_are_mutually_exclusive() -> void:
	var view := _open()
	if not view.has_layout():
		return
	view.select(view.layout.capitals[0])
	view.select_edge(0)
	assert_eq(view.selected_index(), -1, "picking a link drops the game selection")
	assert_eq(view.selected_edge_index(), 0, "and holds the link")
	view.select(view.layout.capitals[0])
	assert_eq(view.selected_edge_index(), -1, "picking a game drops the link selection")

func test_edge_details_refuses_a_bad_index() -> void:
	var view := _open()
	if not view.has_layout():
		return
	assert_true(view.edge_details(-1).is_empty(), "no link below zero")
	assert_true(view.edge_details(view.layout.edge_count()).is_empty(), "none past the end")

# Every link on the map must be describable, or clicking one would open a blank
# card. Direction can be missing only if the catalog lost the authored edge.
func test_every_link_on_the_map_can_be_described() -> void:
	var view := _open()
	if not view.has_layout():
		return
	for e in range(view.layout.edge_count()):
		var d: Dictionary = view.edge_details(e)
		assert_false(d.is_empty(), "link %d names its two games" % e)
