extends GutTest

# Tests for the Atlas — the whole influence graph as a star chart.
#
# Two halves. The BAKED LAYOUT (data/atlas_layout.tres, generated by
# tools/bake_atlas.py) has to describe the catalog truthfully and place no two
# stars on top of each other, since the packing is the whole point. The VIEW has
# to build headless, frame itself, pick stars in screen space, and draw the run's
# route once a run is under way.

const ATLAS := preload("res://scripts/ui/AtlasView.gd")
const OVERWORLD := preload("res://scenes/redesign2/Overworld2.tscn")

var _layout: AtlasLayout

func before_all() -> void:
	_layout = ATLAS.load_layout()

func after_each() -> void:
	GameState.reset_run()
	GameLoop2.reset()

func _open() -> AtlasView:
	var view: AtlasView = ATLAS.new()
	add_child_autofree(view)
	return view

# ---------------------------------------------------------------------------
# The baked layout
# ---------------------------------------------------------------------------

func test_layout_resource_exists() -> void:
	assert_not_null(_layout, "data/atlas_layout.tres is baked (run tools/bake_atlas.py)")

func test_layout_covers_every_game() -> void:
	if _layout == null:
		return
	var catalog: int = Data.all_games().size()
	assert_eq(_layout.star_count(), catalog, "every game in the catalog has a star")
	for g in Data.all_games():
		assert_gte(_layout.index_of(g.id), 0, "%s has a position" % g.id)

func test_parallel_arrays_are_the_same_length() -> void:
	if _layout == null:
		return
	var n: int = _layout.star_count()
	assert_eq(_layout.xs.size(), n, "one x per star")
	assert_eq(_layout.ys.size(), n, "one y per star")
	assert_eq(_layout.region.size(), n, "one region per star")
	assert_eq(_layout.hops.size(), n, "one hop count per star")

func test_edges_are_pairs_of_real_stars() -> void:
	if _layout == null:
		return
	assert_eq(_layout.edges.size() % 2, 0, "the edge list is flat pairs")
	assert_gt(_layout.edge_count(), 0, "the sky has links in it")
	var n: int = _layout.star_count()
	for i in range(_layout.edges.size()):
		var idx: int = _layout.edges[i]
		assert_true(idx >= 0 and idx < n, "edge endpoint %d is a real star" % idx)

# The packing exists to guarantee this: two stars drawn at their baked radii
# never overlap. If this fails the layout is wrong, not the renderer.
func test_no_two_stars_overlap() -> void:
	if _layout == null:
		return
	var n: int = _layout.star_count()
	var cell: float = 48.0
	var grid: Dictionary = {}
	for i in range(n):
		var key: Vector2i = Vector2i(int(floor(_layout.xs[i] / cell)), int(floor(_layout.ys[i] / cell)))
		if not grid.has(key):
			grid[key] = []
		(grid[key] as Array).append(i)
	var overlaps: int = 0
	for i in range(n):
		var base: Vector2i = Vector2i(int(floor(_layout.xs[i] / cell)), int(floor(_layout.ys[i] / cell)))
		for ax in range(-1, 2):
			for ay in range(-1, 2):
				for j in grid.get(base + Vector2i(ax, ay), []):
					if int(j) <= i:
						continue
					var need: float = AtlasLayout.star_radius(_layout.degree_of(i)) \
						+ AtlasLayout.star_radius(_layout.degree_of(int(j)))
					if _layout.position_of(i).distance_to(_layout.position_of(int(j))) < need - 0.001:
						overlaps += 1
	assert_eq(overlaps, 0, "no two stars overlap at their drawn radii")

func test_capitals_are_the_highest_degree_games() -> void:
	if _layout == null:
		return
	assert_gt(_layout.capitals.size(), 0, "the sky has capitals")
	var cap_degree: int = _layout.degree_of(_layout.capitals[0])
	for i in range(_layout.star_count()):
		assert_lte(_layout.degree_of(i), cap_degree,
			"no star out-connects the first capital")

func test_every_star_is_in_a_region_or_drifting() -> void:
	if _layout == null:
		return
	for i in range(_layout.star_count()):
		var r: int = _layout.region[i]
		assert_true(r == -1 or (r >= 0 and r < _layout.capitals.size()),
			"star %d has a valid region" % i)
		# A star in a region knows how far it is from its capital; a drifting one doesn't.
		if r >= 0:
			assert_gte(_layout.hops[i], 0, "a placed star has a hop count")

func test_capitals_sit_at_hop_zero_of_their_own_region() -> void:
	if _layout == null:
		return
	for ci in range(_layout.capitals.size()):
		var cap: int = _layout.capitals[ci]
		assert_eq(_layout.region[cap], ci, "capital %d owns its own region" % ci)
		assert_eq(_layout.hops[cap], 0, "a capital is zero hops from itself")

func test_bounds_contain_every_star() -> void:
	if _layout == null:
		return
	for i in range(_layout.star_count()):
		assert_true(_layout.bounds.has_point(_layout.position_of(i)),
			"star %d is inside the baked bounds" % i)

# ---------------------------------------------------------------------------
# The view
# ---------------------------------------------------------------------------

func test_view_builds_headless() -> void:
	var view := _open()
	assert_true(view.has_layout(), "the view loaded the baked layout")
	assert_gt(view.zoom_ratio(), 0.0, "the view framed itself")

func test_neighbors_match_the_baked_edges() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var counted: int = 0
	for i in range(view.layout.star_count()):
		counted += view.neighbors_of(i).size()
	assert_eq(counted, view.layout.edge_count() * 2,
		"each edge shows up once from each end")

func test_neighbors_are_symmetric() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var a: int = view.layout.capitals[0]
	for n in view.neighbors_of(a):
		assert_true(view.neighbors_of(int(n)).has(a),
			"the graph the atlas draws is undirected")

func test_selecting_a_star_lights_its_links() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var cap: int = view.layout.capitals[0]
	view.select(cap)
	assert_eq(view.selected_index(), cap, "the star is selected")
	assert_eq(view._near.size(), view.neighbors_of(cap).size() + 1,
		"the halo is the star plus its neighbours")
	view.select(-1)
	assert_eq(view.selected_index(), -1, "selection clears")
	assert_eq(view._near.size(), 0, "the halo clears with it")

# Screen-space picking is what keeps a 1px dot clickable at overview zoom.
func test_picking_finds_the_star_under_the_cursor() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var target: int = view.layout.capitals[0]
	var at: Vector2 = view.to_screen(view.layout.position_of(target))
	assert_eq(view.pick(at), target, "clicking a star picks it")

func test_picking_empty_sky_returns_nothing() -> void:
	var view := _open()
	if not view.has_layout():
		return
	# Far outside the bounds, so nothing is within the screen-space tolerance.
	var far: Vector2 = view.to_screen(view.layout.bounds.end + Vector2(6000, 6000))
	assert_eq(view.pick(far), -1, "empty sky picks nothing")

func test_focus_game_centres_and_selects() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var id: StringName = view.layout.id_at(view.layout.capitals[0])
	assert_true(view.focus_game(id), "focusing a real game succeeds")
	assert_eq(view.selected_index(), view.layout.capitals[0], "focusing selects it")

func test_focus_unknown_game_is_refused() -> void:
	var view := _open()
	if not view.has_layout():
		return
	assert_false(view.focus_game(&"not_a_real_game"), "an unknown id is refused")

func test_zoom_is_clamped() -> void:
	var view := _open()
	if not view.has_layout():
		return
	for _i in range(60):
		view.zoom_by(2.0, Vector2(400, 300))
	assert_lte(view.zoom_ratio(), AtlasView.ZOOM_MAX + 0.001, "zoom stops at the ceiling")
	for _i in range(60):
		view.zoom_by(0.5, Vector2(400, 300))
	assert_gte(view.zoom_ratio(), AtlasView.ZOOM_MIN - 0.001, "zoom stops at the floor")

func test_hulls_cover_every_region() -> void:
	var view := _open()
	if not view.has_layout():
		return
	assert_eq(view.hulls().size(), view.layout.capitals.size(),
		"every constellation has a hull")
	for hull in view.hulls():
		assert_gt(float(hull["radius"]), 0.0, "a hull has size")

# ---------------------------------------------------------------------------
# Cover art — stars become their box art when you zoom in far enough
# ---------------------------------------------------------------------------

# A cover is inscribed in the circle the packing reserved for its star, so its
# half-diagonal is exactly that radius. This is what lets art replace the dots
# with no second layout pass.
func test_cover_is_inscribed_in_its_reserved_circle() -> void:
	for aspect in [0.5, 1.0, 4.0 / 3.0, 1.5, 2.0]:
		for radius in [2.45, 6.0, 12.1]:
			var s: Vector2 = AtlasView.cover_size(radius, aspect)
			assert_almost_eq(s.length() * 0.5, radius, 0.001,
				"a %0.2f-aspect cover at r=%0.2f fills its circle exactly" % [aspect, radius])
			assert_almost_eq(s.y / s.x, aspect, 0.001, "the cover keeps its aspect ratio")

func test_cover_size_is_degenerate_when_it_should_be() -> void:
	assert_eq(AtlasView.cover_size(0.0, 1.0), Vector2.ZERO, "no radius, no cover")
	assert_eq(AtlasView.cover_size(5.0, 0.0), Vector2.ZERO, "no aspect, no cover")

# The real proof: over the actual catalog, no two covers can overlap, because no
# two reserved circles do.
func test_no_two_covers_can_overlap() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var lay: AtlasLayout = view.layout
	var checked: int = 0
	var overlaps: int = 0
	var cell: float = 48.0
	var grid: Dictionary = {}
	for i in range(lay.star_count()):
		var key := Vector2i(int(floor(lay.xs[i] / cell)), int(floor(lay.ys[i] / cell)))
		if not grid.has(key):
			grid[key] = []
		(grid[key] as Array).append(i)
	for i in range(lay.star_count()):
		var tex_a: Texture2D = view.cover_texture(i)
		if tex_a == null:
			continue
		var box_a := _world_cover_rect(view, lay, i, tex_a)
		var base := Vector2i(int(floor(lay.xs[i] / cell)), int(floor(lay.ys[i] / cell)))
		for ax in range(-1, 2):
			for ay in range(-1, 2):
				for j in grid.get(base + Vector2i(ax, ay), []):
					if int(j) <= i:
						continue
					var tex_b: Texture2D = view.cover_texture(int(j))
					if tex_b == null:
						continue
					checked += 1
					if box_a.intersects(_world_cover_rect(view, lay, int(j), tex_b)):
						overlaps += 1
	assert_gt(checked, 0, "there are neighbouring covers to check")
	assert_eq(overlaps, 0, "no two cover images overlap anywhere in the sky")

func _world_cover_rect(view: AtlasView, lay: AtlasLayout, i: int, tex: Texture2D) -> Rect2:
	var aspect: float = float(tex.get_height()) / float(tex.get_width())
	var reserved: float = AtlasLayout.star_radius(lay.degree_of(i))
	var s: Vector2 = AtlasView.cover_size(reserved, aspect)
	return Rect2(lay.position_of(i) - s * 0.5, s)

func test_most_games_have_cover_art() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var with_art: int = 0
	for i in range(view.layout.star_count()):
		if view.cover_texture(i) != null:
			with_art += 1
	assert_gt(with_art, int(view.layout.star_count() * 0.9),
		"the great majority of stars have box art to show")

func test_drawn_half_height_tracks_what_is_actually_drawn() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var i: int = view.layout.capitals[0]
	assert_gt(view.drawn_half_height(i), 0.0, "something is always drawn for a star")

# The point of a per-star threshold: the best-connected games become art at a
# lower zoom than the fringe does, so the map fills in from its hubs outward.
func test_well_connected_games_become_art_sooner() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var hub: int = view.layout.capitals[0]
	var leaf: int = -1
	for i in range(view.layout.star_count()):
		if view.layout.degree_of(i) == 1 and view.cover_texture(i) != null:
			leaf = i
			break
	if leaf < 0 or view.cover_texture(hub) == null:
		return
	# Zoom up from the overview one step at a time and record which flips first.
	var hub_at: float = -1.0
	var leaf_at: float = -1.0
	view.frame_all()
	for _step in range(120):
		if hub_at < 0.0 and view.shows_cover(hub):
			hub_at = view.zoom_ratio()
		if leaf_at < 0.0 and view.shows_cover(leaf):
			leaf_at = view.zoom_ratio()
		if hub_at > 0.0 and leaf_at > 0.0:
			break
		view.zoom_by(1.1, Vector2(400, 300))
	assert_gt(hub_at, 0.0, "the hub becomes art at some zoom")
	assert_gt(leaf_at, 0.0, "the dead end becomes art at some zoom")
	assert_lt(hub_at, leaf_at,
		"a 124-connection hub shows its cover before a 1-connection game does")

func test_nothing_shows_art_at_the_overview() -> void:
	var view := _open()
	if not view.has_layout():
		return
	view.frame_all()
	assert_eq(view.cover_count(), 0, "the whole-sky overview is dots, not stamps")

func test_everything_on_screen_with_art_shows_it_when_zoomed_right_in() -> void:
	var view := _open()
	if not view.has_layout():
		return
	for _step in range(80):
		view.zoom_by(1.3, Vector2(400, 300))
	# ON SCREEN, because that is what cover_count answers — see the test below for
	# why it is not allowed to answer for the whole sky.
	var vis: Rect2 = view._visible_rect()
	var with_art: int = 0
	for i in range(view.layout.star_count()):
		if vis.has_point(view.to_screen(view.layout.position_of(i))) \
				and view.cover_texture(i) != null:
			with_art += 1
	assert_eq(view.cover_count(), with_art,
		"at maximum zoom every game on screen that has art is showing it")

# The stutter this guards against: `cover_count` runs on every redraw — so on
# every pan and zoom step — and `shows_cover` used to answer by LOADING the cover
# to measure it. Panning the chart therefore walked the whole 845-cover catalog
# through the image decoder a few stars at a time. A star nowhere near the size
# threshold must be answered from its packing radius alone, with the art untouched.
func test_the_overview_decodes_no_cover_art() -> void:
	var view := _open()
	if not view.has_layout():
		return
	view.frame_all()
	assert_eq(view.cover_count(), 0, "nothing is showing art out here")
	var decoded: int = 0
	for a in view._aspect_cache:
		if a > 0.0:
			decoded += 1
	assert_eq(decoded, 0, "and no cover was loaded to work that out")

func test_zooming_in_only_decodes_what_it_draws() -> void:
	var view := _open()
	if not view.has_layout():
		return
	view.frame_all()
	for _step in range(14):
		view.zoom_by(1.3, Vector2(400, 300))
	var decoded: int = 0
	for a in view._aspect_cache:
		if a > 0.0:
			decoded += 1
	assert_lt(decoded, view.layout.star_count(),
		"a zoom step is not allowed to cost the whole catalog")

# ---------------------------------------------------------------------------
# The run trail — the corridor drawn over the sky
# ---------------------------------------------------------------------------

func test_no_trail_without_a_run() -> void:
	var view := _open()
	assert_eq(view.trail_segment_count(), 0, "no run, no trail")

func test_trail_follows_the_run() -> void:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	var view := _open()
	if not view.has_layout():
		return
	assert_gt(view.trail_segment_count(), 0, "a run in progress draws a trail")
	# Every segment is a real edge between two real stars.
	for seg in view._trail:
		var a: int = int(seg[0])
		var b: int = int(seg[1])
		assert_true(a >= 0 and a < view.layout.star_count(), "trail start is a real star")
		assert_true(b >= 0 and b < view.layout.star_count(), "trail end is a real star")
		assert_true(view.neighbors_of(a).has(b), "a trail segment is a real connection")

# --- route focus: the corridor in front, the rest of the sky behind ---------
#
# While a route is drawn, the sky answers "which way do I go" — so the games on
# the route stay at full strength, everything else is pushed back a step, and the
# big gold constellation names stop shouting over the corridor.

func test_a_run_puts_its_whole_route_in_the_route_set() -> void:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	var view := _open()
	if not view.has_layout() or view.trail_segment_count() == 0:
		return
	assert_true(view.showing_route(), "a run in progress is a route on the sky")
	# Every star either road touches is on the route…
	for seg in view._trail:
		assert_true(view.on_route(int(seg[0])), "the road ahead is on the route")
		assert_true(view.on_route(int(seg[1])))
	for seg in view._history:
		assert_true(view.on_route(int(seg[0])), "so is the road already walked")
		assert_true(view.on_route(int(seg[1])))
	# …and so are the two anchors, whatever the roads do.
	assert_true(view.on_route(view.current_index()), "where you stand is on it")
	assert_true(view.on_route(view.amulet_index()), "and so is what you came for")
	# The sky is 751 games; a route is a corridor through it, not most of it.
	assert_lt(view.route_stars().size(), view.layout.star_count() / 2,
		"most of the sky is off-route scenery")

func test_a_catalog_sky_has_no_route_and_dims_nothing() -> void:
	var view := _open()               # no run booted
	assert_false(view.showing_route(), "no run, no route")
	assert_eq(view.route_stars().size(), 0)
	for i in [0, 1, 2]:
		assert_true(view.on_route(i),
			"with nothing to be off, every star draws at full strength")

# The road has to cross the sky, not be stitched out of whatever showed between
# 700 dots: the stars split in two around it, so a game the route has nothing to
# do with is drawn UNDER the corridor and a game on the route still keeps its own
# art on top of it.
func test_the_road_is_drawn_over_the_games_it_has_nothing_to_do_with() -> void:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	var view := _open()
	if not view.has_layout() or view.trail_segment_count() == 0:
		return
	var layers: Array = view.draw_layers()
	var roads: int = layers.find(view.LAYER_ROADS)
	var scenery: int = layers.find(view.LAYER_STARS_OFF_ROUTE)
	var route: int = layers.find(view.LAYER_STARS_ON_ROUTE)
	assert_gt(roads, -1, "the roads are drawn")
	assert_gt(scenery, -1, "so is the scenery")
	assert_gt(route, -1, "and so are the games on the route")
	assert_lt(scenery, roads, "an off-route game goes down BEFORE the road, so the road covers it")
	assert_lt(roads, route, "and the road goes down before the games it runs between")
	assert_false(layers.has(view.LAYER_STARS_ALL),
		"a split sky never draws the single all-stars pass as well")

func test_a_sky_with_no_route_keeps_its_single_star_pass() -> void:
	var view := _open()               # no run booted
	assert_eq(view.draw_layers(), [view.LAYER_ROADS, view.LAYER_STARS_ALL],
		"with no corridor to protect, the sky is one pass with the roads beneath it")

func test_the_route_set_is_rebuilt_when_the_run_moves() -> void:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	var view := _open()
	if not view.has_layout() or view.trail_segment_count() == 0:
		return
	var left: int = view.current_index()
	assert_eq(view.history_segment_count(), 0, "nothing walked yet — this is the first game")
	view.route_stars()                # fill the cache, so a stale one has somewhere to hide
	# The start is the run's first game, so the run opens in the report step — beat
	# it, and the offering that appears is the one the move under test is made from.
	_report_beat(ui)
	ui._end_resolve()
	ui.pick(0)
	ui.report(false)
	view._build_trail()
	view._build_history()
	assert_gt(view.history_segment_count(), 0, "the step just taken is on the record")
	assert_true(view.on_route(view.current_index()),
		"the game just travelled to is on the route, not scenery")
	assert_true(view.on_route(left), "and so is the one it came from, as road walked")
	# THE CACHE, which is what "rebuilt" means here: route_stars() memoises, so the
	# two builders above have to drop it or the sky goes on painting the old route.
	# Checked against a FRESH build rather than against the pre-move set, because
	# the pre-move set is not reliably different: route_stars() is the union of the
	# road AHEAD and the road WALKED, so a step along the optimal path moves the
	# game you left out of one half and into the other and leaves the union
	# identical. That is a correct rebuild that reads exactly like a stale cache —
	# which is why asserting the two differ failed on whichever runs the offering
	# happened to point straight down the route.
	var cached: Dictionary = view.route_stars().duplicate()
	view._route_stars.clear()
	assert_eq(view.route_stars(), cached, "the cached set is the freshly built one")

func test_framing_the_trail_keeps_the_route_on_screen() -> void:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	var view := _open()
	if not view.has_layout() or view.trail_segment_count() == 0:
		return
	view.frame_trail()
	# The current game and the amulet both sit inside the framed view.
	var current: int = view.layout.index_of(GameState.current_game_id)
	var amulet: int = view.layout.index_of(GameState.amulet_game_id)
	var canvas := Rect2(Vector2.ZERO, view._canvas_size())
	for idx in [current, amulet]:
		if idx >= 0:
			assert_true(canvas.grow(4.0).has_point(view.to_screen(view.layout.position_of(idx))),
				"the route's endpoints are framed")

# ---------------------------------------------------------------------------
# Filtered skies — one layout per Settings.game_filter
# ---------------------------------------------------------------------------

# The Atlas has to draw the graph the run actually travels. With an owned-only
# filter a route through an unowned game doesn't exist, so the sky is laid out
# over the owned subgraph rather than being the full map with stars hidden.
func test_owned_sky_holds_only_owned_games() -> void:
	var owned: AtlasLayout = ATLAS.load_layout(Settings.GameFilter.OWNED)
	assert_not_null(owned, "data/atlas_layout_owned.tres is baked")
	if owned == null:
		return
	assert_eq(owned.source_filter, "owned", "the sky knows which filter it is")
	for i in range(owned.star_count()):
		var game: GameData = Data.get_game(owned.id_at(i))
		assert_not_null(game, "every star is a real game")
		if game != null:
			assert_true(game.owned, "%s is owned" % game.id)

func test_owned_sky_is_smaller_than_the_full_one() -> void:
	var owned: AtlasLayout = ATLAS.load_layout(Settings.GameFilter.OWNED)
	if owned == null or _layout == null:
		return
	assert_lt(owned.star_count(), _layout.star_count(),
		"the owned sky is a subset of the whole catalog")
	assert_gt(owned.star_count(), 0, "and it isn't empty")

# It's laid out from scratch, not cropped — so a game's position differs between
# the two skies, and the owned sky picks its own capitals.
func test_owned_sky_is_laid_out_independently() -> void:
	var owned: AtlasLayout = ATLAS.load_layout(Settings.GameFilter.OWNED)
	if owned == null or _layout == null:
		return
	assert_gt(owned.capitals.size(), 0, "the owned sky has its own capitals")
	var moved: int = 0
	for i in range(owned.star_count()):
		var j: int = _layout.index_of(owned.id_at(i))
		if j >= 0 and owned.position_of(i).distance_to(_layout.position_of(j)) > 0.5:
			moved += 1
	assert_gt(moved, owned.star_count() / 2,
		"most stars sit somewhere else than they do on the full map")

func test_owned_sky_has_no_overlapping_stars() -> void:
	var owned: AtlasLayout = ATLAS.load_layout(Settings.GameFilter.OWNED)
	if owned == null:
		return
	var overlaps: int = 0
	for i in range(owned.star_count()):
		for j in range(i + 1, owned.star_count()):
			var need: float = AtlasLayout.star_radius(owned.degree_of(i)) \
				+ AtlasLayout.star_radius(owned.degree_of(j))
			if owned.position_of(i).distance_to(owned.position_of(j)) < need - 0.001:
				overlaps += 1
	assert_eq(overlaps, 0, "the owned sky packs cleanly too")

# Every edge in a filtered sky must have both ends inside that filter — this is
# what stops the map drawing a route the run can't walk.
func test_filtered_sky_edges_stay_inside_the_filter() -> void:
	var owned: AtlasLayout = ATLAS.load_layout(Settings.GameFilter.OWNED)
	if owned == null:
		return
	var e: int = 0
	while e + 1 < owned.edges.size():
		for idx in [owned.edges[e], owned.edges[e + 1]]:
			var game: GameData = Data.get_game(owned.id_at(int(idx)))
			assert_true(game != null and game.owned, "both ends of a link are owned")
		e += 2

func test_the_view_opens_the_sky_matching_the_active_filter() -> void:
	var previous: int = Settings.game_filter
	Settings.game_filter = Settings.GameFilter.OWNED
	var view := _open()
	if view.has_layout():
		assert_eq(view.layout.source_filter, "owned",
			"opening the Atlas under an owned-only filter shows the owned sky")
	Settings.game_filter = previous

func test_an_unbaked_filter_falls_back_to_the_full_sky() -> void:
	# 99 is not a real GameFilter value, so nothing is baked for it.
	var fallback: AtlasLayout = ATLAS.load_layout(99)
	assert_not_null(fallback, "an unknown filter still gets a map")
	if fallback != null:
		assert_eq(fallback.source_filter, "all", "and it's the full one")

# ---------------------------------------------------------------------------
# Line hierarchy — background links, a clicked game's connections, the route
# ---------------------------------------------------------------------------

# Clicking a game must light up ALL of its connections, not a sample of them.
func test_clicking_a_game_lights_every_one_of_its_connections() -> void:
	var view := _open()
	if not view.has_layout():
		return
	for target in [view.layout.capitals[0], view.layout.capitals[3]]:
		view.select(target)
		var lit: int = 0
		var e: int = 0
		while e + 1 < view.layout.edges.size():
			var a: int = view.layout.edges[e]
			var b: int = view.layout.edges[e + 1]
			e += 2
			if a == target or b == target:
				lit += 1
		assert_eq(lit, view.neighbors_of(target).size(),
			"%s lights all %d of its links" % [view.layout.id_at(target), lit])
		assert_eq(view._near.size(), lit + 1,
			"and every game they reach is in the halo, plus the game itself")

# A dead end has exactly one connection and it still highlights.
func test_a_one_connection_game_still_highlights() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var leaf: int = -1
	for i in range(view.layout.star_count()):
		if view.layout.degree_of(i) == 1:
			leaf = i
			break
	if leaf < 0:
		return
	view.select(leaf)
	assert_eq(view._near.size(), 2, "a dead end highlights itself and its one neighbour")

func test_selection_survives_zooming_out_past_the_link_threshold() -> void:
	var view := _open()
	if not view.has_layout():
		return
	view.select(view.layout.capitals[0])
	for _i in range(30):
		view.zoom_by(0.6, Vector2(400, 300))
	assert_lt(view.zoom_ratio(), AtlasView.ZOOM_LINKS,
		"we are zoomed out past where background links stop drawing")
	assert_eq(view.selected_index(), view.layout.capitals[0],
		"the clicked game stays selected, so its connections still draw")

# The route is a distinct treatment, not a brighter background link — the three
# line colours must stay tellable apart.
func test_route_selection_and_background_lines_are_distinct() -> void:
	var route: Color = AtlasView.COL_TRAIL
	var picked: Color = AtlasView.COL_SELECTED_EDGE
	var backdrop: Color = AtlasView.COL_EDGE
	assert_gt(_separation(route, picked), 0.25, "the route can't be mistaken for a selection")
	assert_gt(_separation(route, backdrop), 0.25, "or for a background link")
	assert_gt(picked.a, backdrop.a, "a clicked game's links are stronger than the backdrop")

func _separation(a: Color, b: Color) -> float:
	return absf(a.r - b.r) + absf(a.g - b.g) + absf(a.b - b.b)

func test_walked_and_remaining_route_are_told_apart() -> void:
	assert_gt(_separation(AtlasView.COL_TRAIL, AtlasView.COL_HISTORY), 0.4,
		"the road behind you doesn't look like the road ahead")

# The route drawn on the atlas is exactly the DAG the run minimap draws.
func test_route_matches_the_run_minimap_exactly() -> void:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	var view := _open()
	if not view.has_layout() or view.trail_segment_count() == 0:
		return
	var dag: Dictionary = RunGraph.shortest_path_dag(
		GameState.current_game_id, GameState.amulet_game_id)
	var expected: Dictionary = {}
	for edge in dag.get("edges", []):
		expected["%s>%s" % [edge["from"], edge["to"]]] = true
	assert_eq(view.trail_segment_count(), expected.size(),
		"the atlas route has one segment per minimap edge")
	for seg in view._trail:
		var key: String = "%s>%s" % [view.layout.id_at(int(seg[0])), view.layout.id_at(int(seg[1]))]
		assert_true(expected.has(key), "%s is an edge the minimap also draws" % key)

# Selecting a game must not hide the route — it's the one thing that stays.
func test_the_route_survives_selecting_something_else() -> void:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	var view := _open()
	if not view.has_layout():
		return
	var before: int = view.trail_segment_count()
	if before == 0:
		return
	view.select(view.layout.capitals[0])
	assert_eq(view.trail_segment_count(), before,
		"clicking a game elsewhere leaves the route to the Amulet drawn")

# ---------------------------------------------------------------------------
# Route arrowheads — which way the road runs
# ---------------------------------------------------------------------------

func test_arrows_clear_the_stars_at_both_ends() -> void:
	var pad_a: float = 30.0
	var pad_b: float = 18.0
	var size: float = 14.0
	var offsets: PackedFloat32Array = AtlasView.route_arrow_offsets(400.0, pad_a, pad_b, size)
	assert_gt(offsets.size(), 0, "a long segment carries arrows")
	for t in offsets:
		assert_gte(t, pad_a, "no arrow sits on the star it leaves")
		assert_lte(t, 400.0 - pad_b, "and none sits on the star it reaches")

func test_a_long_segment_gets_several_arrows() -> void:
	var few: PackedFloat32Array = AtlasView.route_arrow_offsets(160.0, 6.0, 6.0, 12.0)
	var many: PackedFloat32Array = AtlasView.route_arrow_offsets(900.0, 6.0, 6.0, 12.0)
	assert_gt(many.size(), few.size(),
		"a route crossing the sky gets more arrows than a short hop")
	assert_gte(few.size(), 1, "even a modest segment gets one")

func test_arrows_are_evenly_spaced() -> void:
	var offsets: PackedFloat32Array = AtlasView.route_arrow_offsets(900.0, 10.0, 10.0, 12.0)
	if offsets.size() < 3:
		return
	var first_gap: float = offsets[1] - offsets[0]
	for i in range(2, offsets.size()):
		assert_almost_eq(offsets[i] - offsets[i - 1], first_gap, 0.01,
			"the spacing between arrowheads is uniform")

# A plain line beats a smudge: too short to hold an arrowhead means no arrowhead.
func test_a_short_segment_gets_no_arrow() -> void:
	assert_eq(AtlasView.route_arrow_offsets(20.0, 8.0, 8.0, 14.0).size(), 0,
		"a segment swallowed by its endpoints carries nothing")
	assert_eq(AtlasView.route_arrow_offsets(0.0, 0.0, 0.0, 12.0).size(), 0,
		"a zero-length segment carries nothing")
	assert_eq(AtlasView.route_arrow_offsets(400.0, 0.0, 0.0, 0.0).size(), 0,
		"a zero-size arrow is never placed")

# Arrows have to point from the game nearer you toward the game nearer the
# Amulet, or they'd send the player the wrong way.
func test_route_segments_run_toward_the_amulet() -> void:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	var view := _open()
	if not view.has_layout() or view.trail_segment_count() == 0:
		return
	var to_amulet: Dictionary = RunGraph.bfs_distances(GameState.amulet_game_id)
	for seg in view._trail:
		var from_id: StringName = view.layout.id_at(int(seg[0]))
		var to_id: StringName = view.layout.id_at(int(seg[1]))
		assert_true(to_amulet.has(from_id) and to_amulet.has(to_id),
			"both ends of a route segment can reach the Amulet")
		assert_eq(int(to_amulet[to_id]), int(to_amulet[from_id]) - 1,
			"every arrow points one step closer to the Amulet")

# ---------------------------------------------------------------------------
# The path taken — where the player has actually been this run
# ---------------------------------------------------------------------------

# This is a genuinely different road from the route ahead: shortest_path_dag is
# recomputed from where the player stands TO the Amulet, so it never contains a
# game already behind them.
func test_no_path_taken_before_the_run_moves() -> void:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	var view := _open()
	assert_eq(view.history_segment_count(), 0,
		"standing on the starting game, nothing has been walked yet")

func test_path_taken_grows_as_the_player_moves() -> void:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	var start_id: StringName = GameState.current_game_id
	var next: Array = RunGraph.neighbors(start_id)
	if next.is_empty():
		return
	GameState.set_current_game(next[0])
	var view := _open()
	if not view.has_layout():
		return
	assert_eq(view.history_segment_count(), 1, "one hop walked, one segment drawn")
	var seg: Array = view._history[0]
	assert_eq(view.layout.id_at(int(seg[0])), start_id, "it starts where the run started")
	assert_eq(view.layout.id_at(int(seg[1])), StringName(next[0]), "and ends where the player is")
	assert_false(bool(seg[2]), "a normal move follows a real connection")

func test_path_taken_follows_the_order_the_games_were_visited() -> void:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	# Walk three real connections — from a HUB, and always to the best-connected
	# game not yet stood on.
	#
	# It used to walk from wherever the run's random start landed, taking the first
	# unvisited neighbour it found, and give up quietly when it ran out. That is a
	# dead end waiting to happen: `visited_games` is a set, so a walk that wanders
	# into the fringe has nowhere unvisited left to go, and the test then asserted
	# nothing at all and reported itself Risky. Starting at the best-connected game
	# in the catalog and steering toward degree keeps the walk in territory that
	# always has somewhere to go, so the case under test is reached every run.
	var hubs: Array = RunGraph.hub_ids(1)
	if hubs.is_empty():
		pass_test("no graph to walk in this catalog")
		return
	GameState.set_current_game(StringName(hubs[0]))
	for _hop in range(3):
		var best: StringName = &""
		var best_degree: int = -1
		for candidate in RunGraph.neighbors(GameState.current_game_id):
			if GameState.visited_games.has(candidate) or candidate == GameState.current_game_id:
				continue
			var d: int = RunGraph.degree(candidate)
			if d > best_degree:
				best_degree = d
				best = candidate
		if best == &"":
			break
		GameState.set_current_game(best)
	var view := _open()
	if not view.has_layout():
		pass_test("no baked sky in this checkout — run tools/bake_atlas.py")
		return
	assert_gte(view.history_segment_count(), 2,
		"walking out from a hub records a history to check")
	var walked: Array = GameState.visited_games.duplicate()
	walked.append(GameState.current_game_id)
	assert_eq(view.history_segment_count(), walked.size() - 1,
		"one segment per hop actually taken")
	for i in range(view.history_segment_count()):
		var seg: Array = view._history[i]
		assert_eq(view.layout.id_at(int(seg[0])), StringName(walked[i]),
			"segment %d leaves the right game" % i)
		assert_eq(view.layout.id_at(int(seg[1])), StringName(walked[i + 1]),
			"segment %d arrives at the next one" % i)

# Teleport and Winged Boots move the player without traversing a link, so that
# hop is flagged and drawn dashed rather than passed off as a road.
func test_a_hop_with_no_connection_is_flagged_as_a_jump() -> void:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	var start_id: StringName = GameState.current_game_id
	# Find a game that is definitely NOT connected to the start.
	var stranger: StringName = &""
	var linked: Array = RunGraph.neighbors(start_id)
	for g in Data.all_games():
		if g.id != start_id and not linked.has(g.id):
			stranger = g.id
			break
	if stranger == &"":
		return
	GameState.set_current_game(stranger)
	var view := _open()
	if not view.has_layout() or view.history_segment_count() == 0:
		return
	assert_true(bool(view._history[0][2]),
		"a move with no link between the two games reads as a jump")

func test_path_taken_and_route_ahead_are_separate_roads() -> void:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	var next: Array = RunGraph.neighbors(GameState.current_game_id)
	if next.is_empty():
		return
	GameState.set_current_game(next[0])
	var view := _open()
	if not view.has_layout():
		return
	assert_gt(view.history_segment_count(), 0, "there is a road behind")
	# No segment appears on both roads: the DAG starts where the player stands.
	var behind: Dictionary = {}
	for seg in view._history:
		behind["%d>%d" % [int(seg[0]), int(seg[1])]] = true
	for seg in view._trail:
		assert_false(behind.has("%d>%d" % [int(seg[0]), int(seg[1])]),
			"the road ahead never repeats a stretch already walked")

func test_my_run_framing_covers_both_roads() -> void:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	var next: Array = RunGraph.neighbors(GameState.current_game_id)
	if next.is_empty():
		return
	var start_id: StringName = GameState.current_game_id
	GameState.set_current_game(next[0])
	var view := _open()
	if not view.has_layout() or view.history_segment_count() == 0:
		return
	view.frame_trail()
	var canvas := Rect2(Vector2.ZERO, view._canvas_size()).grow(4.0)
	var origin: int = view.layout.index_of(start_id)
	if origin >= 0:
		assert_true(canvas.has_point(view.to_screen(view.layout.position_of(origin))),
			"framing the run includes where it began, not just the road ahead")

# ---------------------------------------------------------------------------
# Staleness — the baked skies are build artefacts, and they can go out of date
# ---------------------------------------------------------------------------
#
# data/atlas_layout*.tres are generated by tools/bake_atlas.py and committed. If
# the catalog changes and the bake isn't re-run — an import that half-failed, a
# hand-edited .tres, a merge that took one side — the Atlas keeps drawing the old
# sky and nothing complains. These tests make that loud.
#
# If one fails, the fix is almost always:  python3 tools/bake_atlas.py --all-filters

# The undirected edge set the catalog describes right now, as "a|b" keys with the
# pair sorted, so it can be compared to a bake regardless of which way round each
# edge was stored.
func _catalog_edge_keys(only_owned: bool = false, only_downloaded: bool = false) -> Dictionary:
	var present: Dictionary = {}
	for g in Data.all_games():
		if only_owned and not g.owned:
			continue
		if only_downloaded and g.file_location.strip_edges() == "":
			continue
		present[g.id] = true
	var keys: Dictionary = {}
	for g in Data.all_games():
		if not present.has(g.id):
			continue
		for other in g.games_influenced:
			if not present.has(other) or other == g.id:
				continue
			var a: String = String(g.id)
			var b: String = String(other)
			keys["%s|%s" % ([a, b] if a < b else [b, a])] = true
	return keys

func _baked_edge_keys(lay: AtlasLayout) -> Dictionary:
	var keys: Dictionary = {}
	var e: int = 0
	while e + 1 < lay.edges.size():
		var a: String = String(lay.id_at(lay.edges[e]))
		var b: String = String(lay.id_at(lay.edges[e + 1]))
		keys["%s|%s" % ([a, b] if a < b else [b, a])] = true
		e += 2
	return keys

# Star count alone doesn't catch a changed CONNECTION — add a link between two
# existing games and the star count is identical while the map is wrong.
func test_baked_sky_matches_the_catalogs_connections() -> void:
	if _layout == null:
		return
	var want: Dictionary = _catalog_edge_keys()
	var have: Dictionary = _baked_edge_keys(_layout)
	var missing: Array = []
	for k in want:
		if not have.has(k):
			missing.append(k)
	var extra: Array = []
	for k in have:
		if not want.has(k):
			extra.append(k)
	assert_eq(missing.size(), 0,
		"connections in the catalog but not in the bake (re-run tools/bake_atlas.py): %s"
		% str(missing.slice(0, 5)))
	assert_eq(extra.size(), 0,
		"connections in the bake but no longer in the catalog: %s" % str(extra.slice(0, 5)))

func test_baked_sky_matches_the_catalogs_games() -> void:
	if _layout == null:
		return
	var baked: Dictionary = {}
	for i in range(_layout.star_count()):
		baked[_layout.id_at(i)] = true
	for g in Data.all_games():
		assert_true(baked.has(g.id), "%s is in the catalog but has no star" % g.id)
	assert_eq(baked.size(), Data.all_games().size(), "and the bake holds nothing extra")

func test_filtered_skies_are_baked_from_the_same_catalog() -> void:
	for spec in [[Settings.GameFilter.OWNED, true, false], [Settings.GameFilter.DOWNLOADED, false, true]]:
		var lay: AtlasLayout = ATLAS.load_layout(int(spec[0]))
		if lay == null or lay.source_filter == "all":
			continue
		var want: Dictionary = _catalog_edge_keys(bool(spec[1]), bool(spec[2]))
		var have: Dictionary = _baked_edge_keys(lay)
		assert_eq(have.size(), want.size(),
			"the '%s' sky has as many links as that filter's catalog does" % lay.source_filter)
		for k in want:
			assert_true(have.has(k), "'%s' sky is missing %s" % [lay.source_filter, k])

# Degrees are read off the baked edge list, so a stale bake would also mis-size
# every star. Check them against the catalog directly.
func test_star_sizes_match_the_catalogs_connection_counts() -> void:
	if _layout == null:
		return
	var degree: Dictionary = {}
	for g in Data.all_games():
		degree[g.id] = 0
	for g in Data.all_games():
		for other in g.games_influenced:
			if degree.has(other) and other != g.id:
				degree[g.id] = int(degree[g.id]) + 1
				degree[other] = int(degree[other]) + 1
	for i in range(_layout.star_count()):
		assert_eq(_layout.degree_of(i), int(degree.get(_layout.id_at(i), -1)),
			"%s is drawn at the size its connection count says" % _layout.id_at(i))

# ---------------------------------------------------------------------------
# Connections — clicking a link, and the evidence behind it
# ---------------------------------------------------------------------------

func test_connection_evidence_is_imported() -> void:
	var with_source: int = 0
	var dev_series: int = 0
	var misaligned: int = 0
	for g in Data.all_games():
		# The evidence arrays are index-aligned with games_influenced; a short one
		# would silently attribute a source to the wrong connection.
		if g.influence_sources.size() != g.games_influenced.size() \
				or g.influence_relations.size() != g.games_influenced.size():
			misaligned += 1
		for src in g.influence_sources:
			if String(src).strip_edges() != "":
				with_source += 1
		for rel in g.influence_relations:
			if String(rel).strip_edges() != "":
				dev_series += 1
	assert_eq(misaligned, 0, "every game's evidence lines up with its connections")
	assert_gt(with_source, 500, "most connections carry a source (the sheet has ~880)")
	assert_gt(dev_series, 50, "the sequel / same-devs flag came through too")

func test_influence_is_described_in_the_authored_direction() -> void:
	var older: GameData = Data.get_game(&"rogue")
	var newer: GameData = Data.get_game(&"brogue")
	if older == null or newer == null:
		return
	# Asked either way round, the answer names the influencer as the source.
	for pair in [[older, newer], [newer, older]]:
		var d: Dictionary = GameData.describe_influence(pair[0], pair[1])
		assert_false(d.is_empty(), "Rogue and Brogue are connected")
		assert_eq((d["from"] as GameData).id, older.id, "Rogue is the influencer")
		assert_eq((d["to"] as GameData).id, newer.id, "Brogue is the influenced")

func test_unconnected_games_describe_nothing() -> void:
	var a: GameData = Data.get_game(&"rogue")
	var b: GameData = Data.get_game(&"balatro")
	if a == null or b == null:
		return
	assert_true(GameData.describe_influence(a, b).is_empty(),
		"two games with no link between them have nothing to describe")

func test_only_real_urls_are_offered_as_openable() -> void:
	assert_true(GameData.is_openable_source("https://roguebasin.com/index.php/Brogue"))
	assert_true(GameData.is_openable_source("  http://example.com/x  "))
	assert_false(GameData.is_openable_source("check folder"))
	assert_false(GameData.is_openable_source("game credits"))
	assert_false(GameData.is_openable_source(""))

func test_clicking_a_link_picks_it() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var e: int = 0
	var a: int = view.layout.edges[0]
	var b: int = view.layout.edges[1]
	# The midpoint of a link is unambiguously on that link.
	var mid: Vector2 = (view.to_screen(view.layout.position_of(a))
		+ view.to_screen(view.layout.position_of(b))) * 0.5
	assert_eq(view.pick_edge(mid), e, "clicking the middle of a link picks it")

func test_empty_sky_picks_no_link() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var far: Vector2 = view.to_screen(view.layout.bounds.end + Vector2(9000, 9000))
	assert_eq(view.pick_edge(far), -1, "empty sky has no link under it")

func test_a_link_reports_both_games_and_its_evidence() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var found: int = -1
	for e in range(view.layout.edge_count()):
		if String(view.edge_details(e).get("source", "")) != "":
			found = e
			break
	assert_gte(found, 0, "some link on the map carries a source")
	var d: Dictionary = view.edge_details(found)
	assert_true(d["from"] is GameData and d["to"] is GameData, "both games are named")
	assert_ne((d["from"] as GameData).id, (d["to"] as GameData).id, "and they're different games")
	assert_ne(String(d["source"]), "", "with the evidence behind the claim")

func test_selecting_a_link_and_a_game_are_mutually_exclusive() -> void:
	var view := _open()
	if not view.has_layout():
		return
	view.select(view.layout.capitals[0])
	view.select_edge(0)
	assert_eq(view.selected_index(), -1, "picking a link drops the game selection")
	assert_eq(view.selected_edge_index(), 0, "and holds the link")
	view.select(view.layout.capitals[0])
	assert_eq(view.selected_edge_index(), -1, "picking a game drops the link selection")

func test_edge_details_refuses_a_bad_index() -> void:
	var view := _open()
	if not view.has_layout():
		return
	assert_true(view.edge_details(-1).is_empty(), "no link below zero")
	assert_true(view.edge_details(view.layout.edge_count()).is_empty(), "none past the end")

# Every link on the map must be describable, or clicking one would open a blank
# card. Direction can be missing only if the catalog lost the authored edge.
func test_every_link_on_the_map_can_be_described() -> void:
	var view := _open()
	if not view.has_layout():
		return
	for e in range(view.layout.edge_count()):
		var d: Dictionary = view.edge_details(e)
		assert_false(d.is_empty(), "link %d names its two games" % e)

# ---------------------------------------------------------------------------
# Sequel links, and owned / beaten stars
# ---------------------------------------------------------------------------

func test_sequel_links_are_identified() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var count: int = view.sequel_link_count()
	assert_gt(count, 50, "the sheet's ~112 sequel / same-devs links are found on the map")
	assert_lt(count, view.layout.edge_count(), "but they're a minority of all links")

func test_a_sequel_link_agrees_with_its_card() -> void:
	var view := _open()
	if not view.has_layout():
		return
	for e in range(view.layout.edge_count()):
		var flagged: bool = view.is_sequel_link(e)
		var d: Dictionary = view.edge_details(e)
		var relation: String = String(d.get("relation", ""))
		assert_eq(flagged, relation != "",
			"link %d draws as a sequel exactly when its card says so" % e)

func test_sequel_stroke_is_distinct_from_the_other_lines() -> void:
	assert_gt(_separation(AtlasView.COL_EDGE_SEQUEL, AtlasView.COL_EDGE), 0.3,
		"a sequel link doesn't look like a plain influence")
	assert_gt(_separation(AtlasView.COL_EDGE_SEQUEL, AtlasView.COL_TRAIL), 0.3,
		"nor like the route")

func test_bad_edge_index_is_not_a_sequel() -> void:
	var view := _open()
	if not view.has_layout():
		return
	assert_false(view.is_sequel_link(-1))
	assert_false(view.is_sequel_link(view.layout.edge_count()))

# ---------------------------------------------------------------------------
# Bash and Transmute, as the map shows them
# ---------------------------------------------------------------------------

func _start_run() -> Node:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	return ui

func test_a_bashed_game_is_marked_on_the_map() -> void:
	_start_run()
	var view := _open()
	if not view.has_layout():
		return
	var victim: StringName = view.layout.id_at(view.layout.capitals[0])
	assert_false(view.is_bashed(view.layout.index_of(victim)), "nothing is bashed yet")
	GameState.bash = 1
	assert_true(GameLoop2.bash_game(victim), "the game is bashed")
	assert_true(view.is_bashed(view.layout.index_of(victim)),
		"the map knows it was destroyed")

func test_transmute_pastes_onto_the_spot_and_stays() -> void:
	_start_run()
	GameState.transmute = 1
	var node: StringName = GameState.current_game_id
	var repl: GameData = GameLoop2.transmute_game(node, [])
	assert_not_null(repl, "a replacement was found")
	if repl == null:
		return
	assert_true(GameLoop2.is_transmuted(node), "the node records the paste")
	assert_eq(GameLoop2.game_at(node).id, repl.id, "and now plays the pasted game")
	assert_eq(GameLoop2.original_at(node).id, node, "while remembering what it was")

func test_the_map_draws_the_pasted_game_not_the_old_one() -> void:
	_start_run()
	GameState.transmute = 1
	var node: StringName = GameState.current_game_id
	var repl: GameData = GameLoop2.transmute_game(node, [])
	if repl == null:
		return
	var view := _open()
	if not view.has_layout():
		return
	var i: int = view.layout.index_of(node)
	assert_true(view.is_transmuted(i), "the star is marked as pasted over")
	assert_eq(view.game_at(i).id, repl.id, "and shows the game now at that spot")

# The paste is on the SPOT, so it has to survive everything that redraws the
# offering — that's the difference from the old per-offering behaviour.
func test_a_paste_survives_a_save_and_reload() -> void:
	_start_run()
	GameState.transmute = 1
	var node: StringName = GameState.current_game_id
	var repl: GameData = GameLoop2.transmute_game(node, [])
	if repl == null:
		return
	var saved: Dictionary = GameLoop2.serialize()
	GameLoop2.reset()
	assert_false(GameLoop2.is_transmuted(node), "reset clears it")
	GameLoop2.restore(saved)
	assert_true(GameLoop2.is_transmuted(node), "restoring brings the paste back")
	assert_eq(GameLoop2.game_at(node).id, repl.id, "with the same game on it")

func test_an_untouched_node_reports_its_own_game() -> void:
	_start_run()
	var node: StringName = GameState.current_game_id
	assert_false(GameLoop2.is_transmuted(node), "nothing pasted here")
	assert_eq(GameLoop2.game_at(node).id, node, "so the node plays its own game")
	assert_null(GameLoop2.original_at(node), "and there's no previous game to name")

func test_bashing_a_pasted_node_takes_the_paste_with_it() -> void:
	_start_run()
	GameState.transmute = 1
	var node: StringName = GameState.current_game_id
	if GameLoop2.transmute_game(node, []) == null:
		return
	GameLoop2.transmuted.erase(node)
	assert_false(GameLoop2.is_transmuted(node), "the paste goes with the destroyed slot")

func test_a_run_reset_clears_both() -> void:
	_start_run()
	GameState.bash = 1
	GameState.transmute = 1
	var node: StringName = GameState.current_game_id
	GameLoop2.bash_game(view_safe_neighbor(node))
	GameLoop2.transmute_game(node, [])
	GameLoop2.reset()
	assert_eq(GameLoop2.bashed.size(), 0, "a new run starts with nothing destroyed")
	assert_eq(GameLoop2.transmuted.size(), 0, "and nothing pasted")

func view_safe_neighbor(node: StringName) -> StringName:
	var n: Array = RunGraph.neighbors(node)
	return n[0] if not n.is_empty() else node

# ---------------------------------------------------------------------------
# Pure catalog mode — the sky with no run laid over it
# ---------------------------------------------------------------------------

func _open_pure() -> AtlasView:
	var view: AtlasView = ATLAS.new()
	view.pure_catalog = true
	add_child_autofree(view)
	return view

func test_pure_catalog_draws_no_run() -> void:
	_start_run()
	var view := _open_pure()
	assert_eq(view.trail_segment_count(), 0, "no route to the Amulet in a catalog view")
	assert_eq(view.history_segment_count(), 0, "and no path taken")

func test_pure_catalog_ignores_bashed_games() -> void:
	_start_run()
	var view := _open_pure()
	if not view.has_layout():
		return
	var victim: StringName = view.layout.id_at(view.layout.capitals[0])
	GameState.bash = 1
	GameLoop2.bash_game(victim)
	var i: int = view.layout.index_of(victim)
	assert_false(view.is_bashed(i), "a catalog view doesn't know about this run's bashes")
	# ...while a run view does.
	var run_view := _open()
	assert_true(run_view.is_bashed(i), "but the run's own map does")

func test_pure_catalog_shows_the_real_game_not_a_paste() -> void:
	_start_run()
	GameState.transmute = 1
	var node: StringName = GameState.current_game_id
	var repl: GameData = GameLoop2.transmute_game(node, [])
	if repl == null:
		return
	var view := _open_pure()
	if not view.has_layout():
		return
	var i: int = view.layout.index_of(node)
	assert_false(view.is_transmuted(i), "a catalog view has nothing pasted on it")
	assert_eq(view.game_at(i).id, node, "the spot shows the game the catalog says lives there")

func test_a_run_view_still_shows_the_paste() -> void:
	_start_run()
	GameState.transmute = 1
	var node: StringName = GameState.current_game_id
	var repl: GameData = GameLoop2.transmute_game(node, [])
	if repl == null:
		return
	var view := _open()
	if not view.has_layout():
		return
	assert_eq(view.game_at(view.layout.index_of(node)).id, repl.id,
		"the run's map still shows what was pasted")

# The catalog is the same sky either way — only what's drawn over it differs.
func test_pure_catalog_holds_the_whole_catalog() -> void:
	var view := _open_pure()
	if not view.has_layout():
		return
	assert_eq(view.layout.star_count(), Data.all_games().size(),
		"every game is still on the chart")
	assert_gt(view.layout.edge_count(), 0, "with its connections")

# ---------------------------------------------------------------------------
# Achievement outlines — what you've done with a game, on its rim
# ---------------------------------------------------------------------------

var _saved_stats: Dictionary = {}

func _stub_stats(game_id: StringName, beaten: int, amulets: int) -> void:
	if _saved_stats.is_empty():
		_saved_stats = GameStats.stats.duplicate(true)
	GameStats.stats[String(game_id)] = {"beaten": beaten, "amulets": amulets}

func _restore_stats() -> void:
	if not _saved_stats.is_empty():
		GameStats.stats = _saved_stats
		_saved_stats = {}

func test_an_unplayed_game_is_drawn_at_full_colour() -> void:
	var view := _open_pure()
	if not view.has_layout():
		return
	var i: int = -1
	for k in range(view.layout.star_count()):
		var gid: StringName = view.layout.id_at(k)
		if GameStats.beaten_count(gid) == 0 and GameStats.amulet_wins(gid) == 0:
			i = k
			break
	if i < 0:
		return
	var game: GameData = Data.get_game(view.layout.id_at(i))
	assert_false(view.has_record(i), "nothing earned on it yet")
	assert_eq(view.star_record_color(i).a, 0.0,
		"so no metallic pip — the middle falls back to the genre colour")
	assert_eq(RunGraph.type_color(game.type).a, 1.0,
		"and that colour is drawn at full strength, not dimmed")

func test_a_beaten_game_has_a_silver_middle() -> void:
	var view := _open_pure()
	if not view.has_layout():
		return
	var gid: StringName = view.layout.id_at(0)
	_stub_stats(gid, 3, 0)
	assert_true(view.has_record(0), "beating it fills the middle")
	assert_eq(view.star_record_color(0), AtlasView.COL_BEATEN, "silver for beaten")
	_restore_stats()

func test_an_amulet_win_is_gold_and_outranks_silver() -> void:
	var view := _open_pure()
	if not view.has_layout():
		return
	var gid: StringName = view.layout.id_at(0)
	# A game won on is also a game beaten — gold has to win.
	_stub_stats(gid, 5, 2)
	assert_eq(view.star_record_color(0), AtlasView.COL_AMULET_WIN,
		"gold outranks silver when both apply")
	_restore_stats()

# The record belongs to the Collection. During a run the sky is about the run,
# so the middles stay empty however much of the catalog has been beaten.
func test_the_record_is_drawn_in_the_catalog_but_not_in_a_run() -> void:
	_start_run()
	var gid: StringName = &"rogue"
	_stub_stats(gid, 4, 2)
	var run_view := _open()
	var pure_view := _open_pure()
	if not run_view.has_layout():
		_restore_stats()
		return
	var i: int = run_view.layout.index_of(gid)
	if i < 0:
		_restore_stats()
		return
	assert_true(pure_view.has_record(i), "the catalog view fills its middle")
	assert_eq(pure_view.star_record_color(i), AtlasView.COL_AMULET_WIN, "gold, here")
	assert_false(run_view.has_record(i), "the run's map leaves it empty")
	assert_eq(run_view.star_record_color(i).a, 0.0, "with nothing drawn in it")
	_restore_stats()

# Genre is unaffected by the gating — it's on the rim in both views.
func test_genre_is_drawn_in_both_views() -> void:
	var run_view := _open()
	var pure_view := _open_pure()
	if not run_view.has_layout():
		return
	var game: GameData = Data.get_game(run_view.layout.id_at(0))
	if game == null:
		return
	for view in [run_view, pure_view]:
		assert_eq(RunGraph.type_color(view.game_at(0).type), RunGraph.type_color(game.type),
			"the rim is the game's genre either way")

func test_silver_and_gold_are_tellable_apart() -> void:
	assert_gt(_separation(AtlasView.COL_BEATEN, AtlasView.COL_AMULET_WIN), 0.25,
		"silver and gold don't look alike")
	for t in RunGraph.TYPE_ORDER:
		assert_gt(_separation(AtlasView.COL_BEATEN, RunGraph.type_color(t)), 0.2,
			"nor does silver look like a genre colour")

# Genre now owns the rim at every zoom, which is the point of the swap.
func test_genre_still_reads_on_a_game_with_a_record() -> void:
	var view := _open_pure()
	if not view.has_layout():
		return
	var gid: StringName = view.layout.id_at(0)
	_stub_stats(gid, 2, 1)
	var game: GameData = Data.get_game(gid)
	assert_true(view.has_record(0), "it has a record")
	assert_ne(view.star_record_color(0), RunGraph.type_color(game.type),
		"the middle carries the record, not the genre")
	_restore_stats()

# ---------------------------------------------------------------------------
# Catalog filters — the sky is rebuilt around what survives
#
# `passes_filter` is the membership predicate: it answers "is this game in the
# set the sky should be drawn from". The tests below check the predicate; the
# ones under "Relayout" check that changing a filter actually re-lays the sky
# rather than dimming stars where they stand.
# ---------------------------------------------------------------------------

func test_no_filtering_outside_the_catalog_view() -> void:
	var view := _open()
	if not view.has_layout():
		return
	view._f_type = 0
	for i in range(mini(30, view.layout.star_count())):
		assert_true(view.passes_filter(i), "a run's map has no filter bar and hides nothing")

func test_everything_passes_by_default() -> void:
	var view := _open_pure()
	if not view.has_layout():
		return
	assert_eq(view.filtered_count(), view.layout.star_count(), "nothing is hidden to start")

func test_the_type_filter_keeps_only_that_type() -> void:
	var view := _open_pure()
	if not view.has_layout():
		return
	view._f_type = GameData.GameType.DECKBUILDER
	var shown: int = 0
	for i in range(view.layout.star_count()):
		if view.passes_filter(i):
			shown += 1
			assert_eq(int(Data.get_game(view.layout.id_at(i)).type),
				int(GameData.GameType.DECKBUILDER), "only deckbuilders survive")
	assert_gt(shown, 0, "and some do")
	assert_lt(shown, view.layout.star_count(), "but not all of them")

func test_the_library_filter_keeps_only_owned() -> void:
	var view := _open_pure()
	if not view.has_layout():
		return
	view._f_owned = 1
	for i in range(view.layout.star_count()):
		if view.passes_filter(i):
			assert_true(Data.get_game(view.layout.id_at(i)).owned, "only owned games survive")

func test_not_owned_is_the_complement_of_owned() -> void:
	var view := _open_pure()
	if not view.has_layout():
		return
	view._f_owned = 1
	var owned: int = view.filtered_count()
	view._f_owned = 3
	var unowned: int = view.filtered_count()
	assert_eq(owned + unowned, view.layout.star_count(),
		"owned and not-owned partition the catalog")

func test_filters_combine() -> void:
	var view := _open_pure()
	if not view.has_layout():
		return
	view._f_type = GameData.GameType.ACTION
	var by_type: int = view.filtered_count()
	view._f_owned = 1
	var both: int = view.filtered_count()
	assert_lte(both, by_type, "adding a second filter can only narrow the result")

func test_the_region_filter_keeps_one_constellation() -> void:
	var view := _open_pure()
	if not view.has_layout():
		return
	view._f_region = 0
	for i in range(view.layout.star_count()):
		if view.passes_filter(i):
			assert_eq(view.layout.region[i], 0, "only the chosen constellation survives")

# Region is measured against the BASE sky. After a relayout the drawn sky has
# its own capitals, so asking it "which region is this star in" would answer a
# different question every time; the baked sky's answer is the stable one.
func test_the_region_filter_still_means_the_baked_constellation() -> void:
	var view := _open_pure()
	if not view.has_layout():
		return
	var base: AtlasLayout = view._base_layout
	view._f_region = 0
	view._relayout()
	assert_ne(view.layout, base, "the sky was rebuilt around the region")
	for i in range(view.layout.star_count()):
		var bi: int = base.index_of(view.layout.id_at(i))
		assert_eq(base.region[bi], 0,
			"%s is drawn because it belongs to region 0 of the baked sky"
				% view.layout.id_at(i))

# ---------------------------------------------------------------------------
# Relayout — a filter picks a subgraph and the sky is built around it
# ---------------------------------------------------------------------------

func test_an_unfiltered_catalog_draws_the_baked_sky() -> void:
	var view := _open_pure()
	if not view.has_layout():
		return
	assert_eq(view.layout, view._base_layout,
		"nothing narrows it, so there is nothing to rebuild")

func test_a_filter_rebuilds_the_sky_around_the_survivors() -> void:
	var view := _open_pure()
	if not view.has_layout():
		return
	var before: int = view.layout.star_count()
	view._f_type = GameData.GameType.DECKBUILDER
	view._relayout()
	assert_ne(view.layout, view._base_layout, "a new sky, not the baked one")
	assert_lt(view.layout.star_count(), before, "holding only the survivors")
	for i in range(view.layout.star_count()):
		assert_eq(int(Data.get_game(view.layout.id_at(i)).type),
			int(GameData.GameType.DECKBUILDER), "every star drawn passes the filter")

func test_a_rebuilt_sky_cuts_its_own_constellations() -> void:
	var view := _open_pure()
	if not view.has_layout():
		return
	var baked_caps: Array = []
	for c in view._base_layout.capitals:
		baked_caps.append(String(view._base_layout.id_at(c)))
	view._f_type = GameData.GameType.TRADITIONAL
	view._relayout()
	var built_caps: Array = []
	for c in view.layout.capitals:
		built_caps.append(String(view.layout.id_at(c)))
	assert_gt(built_caps.size(), 0, "the filtered sky has capitals of its own")
	assert_ne(built_caps, baked_caps, "and they are not the full catalog's")

func test_clearing_the_filter_returns_the_baked_sky() -> void:
	var view := _open_pure()
	if not view.has_layout():
		return
	view._f_type = GameData.GameType.ACTION
	view._relayout()
	assert_ne(view.layout, view._base_layout)
	view._f_type = -1
	view._relayout()
	assert_eq(view.layout, view._base_layout,
		"back to the sky that shipped, not a rebuild of it")

func test_a_relayout_drops_the_selection() -> void:
	var view := _open_pure()
	if not view.has_layout():
		return
	view.select(3)
	view._f_owned = 1
	view._relayout()
	assert_eq(view._selected, -1,
		"the old index pointed into a sky that no longer exists")

# ---------------------------------------------------------------------------
# Layout modes
# ---------------------------------------------------------------------------

func test_the_tree_mode_builds_a_tree() -> void:
	var view := _open_pure()
	if not view.has_layout():
		return
	view.set_mode(AtlasView.Mode.TREE)
	assert_true(view.layout.is_tree(), "the drawn sky is a tree")
	assert_eq(view.layout.star_count(), view._base_layout.star_count(),
		"holding the whole catalog, arranged differently")
	assert_eq(String(view.layout.id_at(view._tree_root_index())), "rogue",
		"rooted where the genre is")

func test_switching_back_returns_the_constellations() -> void:
	var view := _open_pure()
	if not view.has_layout():
		return
	view.set_mode(AtlasView.Mode.TREE)
	view.set_mode(AtlasView.Mode.CONSTELLATIONS)
	assert_false(view.layout.is_tree())
	assert_eq(view.layout, view._base_layout, "and with no filter, the baked one")

func test_the_tree_honours_the_filters_too() -> void:
	var view := _open_pure()
	if not view.has_layout():
		return
	view.set_mode(AtlasView.Mode.TREE)
	var whole: int = view.layout.star_count()
	view._f_type = GameData.GameType.STRATEGY
	view._relayout()
	assert_true(view.layout.is_tree(), "still a tree")
	assert_lt(view.layout.star_count(), whole, "of just the strategy games")
	for i in range(view.layout.star_count()):
		assert_eq(int(Data.get_game(view.layout.id_at(i)).type),
			int(GameData.GameType.STRATEGY))

func test_the_run_map_never_relayouts() -> void:
	# Outside the catalog the sky is the run's own baked map: routes are drawn
	# across it and moving the stars underneath them would be a lie.
	var view := _open()
	if not view.has_layout():
		return
	var before: AtlasLayout = view.layout
	view._f_type = GameData.GameType.ACTION
	view._relayout()
	assert_eq(view.layout, before, "a run's map holds still")

func test_the_record_filters_split_the_catalog() -> void:
	var view := _open_pure()
	if not view.has_layout():
		return
	view._f_record = 1
	var beaten: int = view.filtered_count()
	view._f_record = 2
	var never: int = view.filtered_count()
	assert_eq(beaten + never, view.layout.star_count(),
		"beaten and never-beaten account for every game")

# Changing the capital count is a different baked sky, not a filter.
func test_changing_the_capital_count_swaps_the_sky() -> void:
	var view := _open_pure()
	if not view.has_layout():
		return
	var before: int = view.layout.capitals.size()
	view.set_capital_count(12)
	assert_eq(view.layout.capitals.size(), 12, "twelve capitals now")
	assert_ne(view.layout.capitals.size(), before, "which is a different cut")
	assert_eq(view.layout.star_count(), Data.all_games().size(),
		"still the whole catalog, just cut differently")

func test_an_unbaked_capital_count_is_refused() -> void:
	var view := _open_pure()
	if not view.has_layout():
		return
	var before: int = view.layout.capitals.size()
	view.set_capital_count(99)
	assert_eq(view.layout.capitals.size(), before, "a sky that was never baked is ignored")

# A region filter can't survive a re-cut — the indices mean different places.
func test_changing_capitals_clears_the_region_filter() -> void:
	var view := _open_pure()
	if not view.has_layout():
		return
	view._f_region = 1
	view.set_capital_count(6)
	assert_eq(view._f_region, -1, "region indices belong to the sky they came from")

# ---------------------------------------------------------------------------
# The card's cover art — shown WHOLE
#
# The chart inscribes art in a circle and the connection strip is a thumbnail,
# but the card is the panel you opened by CLICKING a game, so nothing may be
# cropped off it.
# ---------------------------------------------------------------------------

func _any_cover() -> Texture2D:
	for game in Data.all_games():
		if game.cover_image != null and game.cover_image.get_width() > 0:
			return game.cover_image
	return null

func test_card_art_keeps_the_whole_picture() -> void:
	var tex: Texture2D = _any_cover()
	assert_not_null(tex, "the catalog has cover art to show")
	if tex == null:
		return
	var box: Vector2 = ATLAS.card_art_size(tex, ATLAS.CARD_ART_WIDTH)
	var want: float = float(tex.get_width()) / float(tex.get_height())
	assert_almost_eq(box.x / box.y, want, 0.001,
		"the frame is the shape of the picture, so none of it is cut")
	assert_lte(box.y, ATLAS.CARD_ART_MAX_HEIGHT, "a tall cover is scaled down, not cropped")
	assert_lte(box.x, ATLAS.CARD_ART_WIDTH, "and never wider than the card")

func test_card_art_refuses_a_degenerate_texture() -> void:
	assert_eq(ATLAS.card_art_size(null, 200.0), Vector2.ZERO, "no texture, no frame")
	assert_eq(ATLAS.card_art_size(_any_cover(), 0.0), Vector2.ZERO, "no width, no frame")

func test_the_clicked_card_never_crops_its_cover() -> void:
	var view := _open()
	if not view.has_layout():
		return
	# The first star that actually has art — that's the card with a picture on it.
	var target: int = -1
	for i in range(view.layout.star_count()):
		if view.cover_texture(i) != null:
			target = i
			break
	assert_gt(target, -1, "some game on the map has cover art")
	view.select(target)
	var art: TextureRect = null
	for c in view._card_box.get_children():
		if c is TextureRect:
			art = c
			break
	assert_not_null(art, "the card shows the cover")
	if art == null:
		return
	assert_eq(art.stretch_mode, TextureRect.STRETCH_KEEP_ASPECT_CENTERED,
		"KEEP_ASPECT_CENTERED — a COVERED cover is a cropped cover")
	assert_almost_eq(art.custom_minimum_size.x / art.custom_minimum_size.y,
		float(art.texture.get_width()) / float(art.texture.get_height()), 0.001,
		"and the frame it sits in is the picture's own shape")

# ---------------------------------------------------------------------------
# The run's two anchors — where you stand and what you came for
# ---------------------------------------------------------------------------

func test_the_sky_knows_where_the_player_is_and_where_the_goal_is() -> void:
	_start_run()
	var view := _open()
	if not view.has_layout():
		return
	assert_eq(view.current_index(), view.layout.index_of(GameState.current_game_id),
		"you-are-here is the star of the game being stood on")
	assert_eq(view.amulet_index(), view.layout.index_of(GameState.amulet_game_id),
		"and the goal is the Amulet's star")
	assert_ne(view.current_index(), -1)
	assert_ne(view.amulet_index(), -1)

func test_both_anchors_are_named_on_the_map() -> void:
	_start_run()
	var view := _open()
	if not view.has_layout():
		return
	assert_true(view.marker_text(view.current_index()).contains("YOU ARE HERE"),
		"the spot you're on says so: %s" % view.marker_text(view.current_index()))
	assert_true(view.marker_text(view.amulet_index()).contains("AMULET"),
		"and so does the goal: %s" % view.marker_text(view.amulet_index()))
	assert_eq(view.marker_color(view.current_index()), ATLAS.COL_YOU)
	assert_eq(view.marker_color(view.amulet_index()), ATLAS.COL_GOAL)
	assert_eq(view.marker_text(-1), "", "nothing else is an anchor")

func test_the_goal_marker_counts_the_steps_left() -> void:
	_start_run()
	var view := _open()
	if not view.has_layout():
		return
	var dist: Dictionary = RunGraph.bfs_distances(GameState.current_game_id)
	var hops: int = int(dist.get(GameState.amulet_game_id, -1))
	assert_eq(view.steps_to_amulet(), hops, "the distance is the graph's own")
	assert_true(view.marker_text(view.amulet_index()).contains(str(hops)),
		"and the marker prints it: %s" % view.marker_text(view.amulet_index()))

func test_the_run_line_names_both_ends() -> void:
	_start_run()
	var view := _open()
	if not view.has_layout():
		return
	var here: GameData = Data.get_game(GameState.current_game_id)
	var goal: GameData = Data.get_game(GameState.amulet_game_id)
	var line: String = view.run_summary()
	assert_true(line.contains(here.display_name), "the HUD line says where you are: %s" % line)
	assert_true(line.contains(goal.display_name), "and where you're going: %s" % line)

func test_the_catalog_view_has_no_anchors() -> void:
	_start_run()
	var view := _open_pure()
	assert_eq(view.current_index(), -1, "the catalog is about the games, not a run")
	assert_eq(view.amulet_index(), -1)
	assert_eq(view.run_summary(), "", "so it says nothing about one")

func test_no_anchors_before_a_run_starts() -> void:
	var view := _open()
	assert_eq(view.current_index(), -1, "nothing to stand on yet")
	assert_eq(view.amulet_index(), -1)
	assert_eq(view.steps_to_amulet(), -1, "and nowhere to go")

func test_framing_an_anchor_puts_it_on_screen() -> void:
	_start_run()
	var view := _open()
	if not view.has_layout():
		return
	for idx in [view.current_index(), view.amulet_index()]:
		view._frame_star(idx)
		var canvas := Rect2(Vector2.ZERO, view._canvas_size())
		assert_true(canvas.grow(4.0).has_point(view.to_screen(view.layout.position_of(idx))),
			"the anchor the button jumps to is in view")


# --- panning ---------------------------------------------------------------
#
# Right-drag is the map-moving button. Left-drag still pans as well, but the
# left button has to decide between "moved the map" and "picked a star", so it
# only counts as a pan past a 5px threshold; the right button only ever pans and
# can be nudged a pixel at a time.

func _press(view: AtlasView, button: int, pressed: bool, at: Vector2 = Vector2(400, 300)) -> void:
	var ev := InputEventMouseButton.new()
	ev.button_index = button
	ev.pressed = pressed
	ev.position = at
	view._on_canvas_input(ev)

func _move(view: AtlasView, by: Vector2) -> void:
	var ev := InputEventMouseMotion.new()
	ev.relative = by
	ev.position = Vector2(400, 300) + by
	view._on_canvas_input(ev)

func test_right_drag_pans_the_chart() -> void:
	var view: AtlasView = _open()
	var before: Vector2 = view._offset
	_press(view, MOUSE_BUTTON_RIGHT, true)
	_move(view, Vector2(60, -25))
	assert_ne(view._offset, before, "holding right and moving pans the sky")
	_press(view, MOUSE_BUTTON_RIGHT, false)
	var parked: Vector2 = view._offset
	_move(view, Vector2(40, 40))
	assert_eq(view._offset, parked, "and it stops when the button comes up")

func test_right_drag_pans_by_a_single_pixel() -> void:
	# No click-vs-drag threshold on this button, because it has nothing to click.
	var view: AtlasView = _open()
	var before: Vector2 = view._offset
	_press(view, MOUSE_BUTTON_RIGHT, true)
	_move(view, Vector2(1, 0))
	assert_ne(view._offset, before, "a one-pixel right-drag still moves the map")
	_press(view, MOUSE_BUTTON_RIGHT, false)

func test_right_drag_never_selects_a_star() -> void:
	var view: AtlasView = _open()
	view.select(-1)
	_press(view, MOUSE_BUTTON_RIGHT, true)
	_press(view, MOUSE_BUTTON_RIGHT, false)
	assert_eq(view._selected, -1, "the pan button is not a picking button")

func test_left_drag_still_pans() -> void:
	var view: AtlasView = _open()
	var before: Vector2 = view._offset
	_press(view, MOUSE_BUTTON_LEFT, true)
	_move(view, Vector2(50, 30))
	assert_ne(view._offset, before, "left-drag keeps working for anyone used to it")
	_press(view, MOUSE_BUTTON_LEFT, false)

# Report the game as completed AND tick the row for the body that walked on with
# it. This is what a bare `report(true)` used to do in one flag, back when that
# body was the game's own enemy and beating the game answered for it; it is spelled
# out now because the flag only records the GAME any more (GameLoop2.arrivals),
# and clearing an enemy is ticking its checklist row like any other.
func _report_beat(ui) -> void:
	var landed: Dictionary = GameLoop2.arrival()
	ui.report(true, [] if landed.is_empty() else [int(landed["instance"])])
