extends GutTest

# Tests for the Atlas — the whole influence graph as a star chart.
#
# Two halves. The BAKED LAYOUT (data/atlas_layout.tres, generated by
# tools/bake_atlas.py) has to describe the catalog truthfully and place no two
# stars on top of each other, since the packing is the whole point. The VIEW has
# to build headless, frame itself, pick stars in screen space, and draw the run's
# route once a run is under way.

const ATLAS := preload("res://scripts/ui/AtlasView.gd")
const OVERWORLD := preload("res://scenes/redesign2/Overworld2.tscn")

var _layout: AtlasLayout

func before_all() -> void:
	_layout = ATLAS.load_layout()

func after_each() -> void:
	GameState.reset_run()
	GameLoop2.reset()

func _open() -> AtlasView:
	var view: AtlasView = ATLAS.new()
	add_child_autofree(view)
	return view

# ---------------------------------------------------------------------------
# The baked layout
# ---------------------------------------------------------------------------

func test_layout_resource_exists() -> void:
	assert_not_null(_layout, "data/atlas_layout.tres is baked (run tools/bake_atlas.py)")

func test_layout_covers_every_game() -> void:
	if _layout == null:
		return
	var catalog: int = Data.all_games().size()
	assert_eq(_layout.star_count(), catalog, "every game in the catalog has a star")
	for g in Data.all_games():
		assert_gte(_layout.index_of(g.id), 0, "%s has a position" % g.id)

func test_parallel_arrays_are_the_same_length() -> void:
	if _layout == null:
		return
	var n: int = _layout.star_count()
	assert_eq(_layout.xs.size(), n, "one x per star")
	assert_eq(_layout.ys.size(), n, "one y per star")
	assert_eq(_layout.region.size(), n, "one region per star")
	assert_eq(_layout.hops.size(), n, "one hop count per star")

func test_edges_are_pairs_of_real_stars() -> void:
	if _layout == null:
		return
	assert_eq(_layout.edges.size() % 2, 0, "the edge list is flat pairs")
	assert_gt(_layout.edge_count(), 0, "the sky has links in it")
	var n: int = _layout.star_count()
	for i in range(_layout.edges.size()):
		var idx: int = _layout.edges[i]
		assert_true(idx >= 0 and idx < n, "edge endpoint %d is a real star" % idx)

# The packing exists to guarantee this: two stars drawn at their baked radii
# never overlap. If this fails the layout is wrong, not the renderer.
func test_no_two_stars_overlap() -> void:
	if _layout == null:
		return
	var n: int = _layout.star_count()
	var cell: float = 48.0
	var grid: Dictionary = {}
	for i in range(n):
		var key: Vector2i = Vector2i(int(floor(_layout.xs[i] / cell)), int(floor(_layout.ys[i] / cell)))
		if not grid.has(key):
			grid[key] = []
		(grid[key] as Array).append(i)
	var overlaps: int = 0
	for i in range(n):
		var base: Vector2i = Vector2i(int(floor(_layout.xs[i] / cell)), int(floor(_layout.ys[i] / cell)))
		for ax in range(-1, 2):
			for ay in range(-1, 2):
				for j in grid.get(base + Vector2i(ax, ay), []):
					if int(j) <= i:
						continue
					var need: float = AtlasLayout.star_radius(_layout.degree_of(i)) \
						+ AtlasLayout.star_radius(_layout.degree_of(int(j)))
					if _layout.position_of(i).distance_to(_layout.position_of(int(j))) < need - 0.001:
						overlaps += 1
	assert_eq(overlaps, 0, "no two stars overlap at their drawn radii")

func test_capitals_are_the_highest_degree_games() -> void:
	if _layout == null:
		return
	assert_gt(_layout.capitals.size(), 0, "the sky has capitals")
	var cap_degree: int = _layout.degree_of(_layout.capitals[0])
	for i in range(_layout.star_count()):
		assert_lte(_layout.degree_of(i), cap_degree,
			"no star out-connects the first capital")

func test_every_star_is_in_a_region_or_drifting() -> void:
	if _layout == null:
		return
	for i in range(_layout.star_count()):
		var r: int = _layout.region[i]
		assert_true(r == -1 or (r >= 0 and r < _layout.capitals.size()),
			"star %d has a valid region" % i)
		# A star in a region knows how far it is from its capital; a drifting one doesn't.
		if r >= 0:
			assert_gte(_layout.hops[i], 0, "a placed star has a hop count")

func test_capitals_sit_at_hop_zero_of_their_own_region() -> void:
	if _layout == null:
		return
	for ci in range(_layout.capitals.size()):
		var cap: int = _layout.capitals[ci]
		assert_eq(_layout.region[cap], ci, "capital %d owns its own region" % ci)
		assert_eq(_layout.hops[cap], 0, "a capital is zero hops from itself")

func test_bounds_contain_every_star() -> void:
	if _layout == null:
		return
	for i in range(_layout.star_count()):
		assert_true(_layout.bounds.has_point(_layout.position_of(i)),
			"star %d is inside the baked bounds" % i)

# ---------------------------------------------------------------------------
# The view
# ---------------------------------------------------------------------------

func test_view_builds_headless() -> void:
	var view := _open()
	assert_true(view.has_layout(), "the view loaded the baked layout")
	assert_gt(view.zoom_ratio(), 0.0, "the view framed itself")

func test_neighbors_match_the_baked_edges() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var counted: int = 0
	for i in range(view.layout.star_count()):
		counted += view.neighbors_of(i).size()
	assert_eq(counted, view.layout.edge_count() * 2,
		"each edge shows up once from each end")

func test_neighbors_are_symmetric() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var a: int = view.layout.capitals[0]
	for n in view.neighbors_of(a):
		assert_true(view.neighbors_of(int(n)).has(a),
			"the graph the atlas draws is undirected")

func test_selecting_a_star_lights_its_links() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var cap: int = view.layout.capitals[0]
	view.select(cap)
	assert_eq(view.selected_index(), cap, "the star is selected")
	assert_eq(view._near.size(), view.neighbors_of(cap).size() + 1,
		"the halo is the star plus its neighbours")
	view.select(-1)
	assert_eq(view.selected_index(), -1, "selection clears")
	assert_eq(view._near.size(), 0, "the halo clears with it")

# Screen-space picking is what keeps a 1px dot clickable at overview zoom.
func test_picking_finds_the_star_under_the_cursor() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var target: int = view.layout.capitals[0]
	var at: Vector2 = view.to_screen(view.layout.position_of(target))
	assert_eq(view.pick(at), target, "clicking a star picks it")

func test_picking_empty_sky_returns_nothing() -> void:
	var view := _open()
	if not view.has_layout():
		return
	# Far outside the bounds, so nothing is within the screen-space tolerance.
	var far: Vector2 = view.to_screen(view.layout.bounds.end + Vector2(6000, 6000))
	assert_eq(view.pick(far), -1, "empty sky picks nothing")

func test_focus_game_centres_and_selects() -> void:
	var view := _open()
	if not view.has_layout():
		return
	var id: StringName = view.layout.id_at(view.layout.capitals[0])
	assert_true(view.focus_game(id), "focusing a real game succeeds")
	assert_eq(view.selected_index(), view.layout.capitals[0], "focusing selects it")

func test_focus_unknown_game_is_refused() -> void:
	var view := _open()
	if not view.has_layout():
		return
	assert_false(view.focus_game(&"not_a_real_game"), "an unknown id is refused")

func test_zoom_is_clamped() -> void:
	var view := _open()
	if not view.has_layout():
		return
	for _i in range(60):
		view.zoom_by(2.0, Vector2(400, 300))
	assert_lte(view.zoom_ratio(), AtlasView.ZOOM_MAX + 0.001, "zoom stops at the ceiling")
	for _i in range(60):
		view.zoom_by(0.5, Vector2(400, 300))
	assert_gte(view.zoom_ratio(), AtlasView.ZOOM_MIN - 0.001, "zoom stops at the floor")

func test_hulls_cover_every_region() -> void:
	var view := _open()
	if not view.has_layout():
		return
	assert_eq(view.hulls().size(), view.layout.capitals.size(),
		"every constellation has a hull")
	for hull in view.hulls():
		assert_gt(float(hull["radius"]), 0.0, "a hull has size")

# ---------------------------------------------------------------------------
# The run trail — the corridor drawn over the sky
# ---------------------------------------------------------------------------

func test_no_trail_without_a_run() -> void:
	var view := _open()
	assert_eq(view.trail_segment_count(), 0, "no run, no trail")

func test_trail_follows_the_run() -> void:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	var view := _open()
	if not view.has_layout():
		return
	assert_gt(view.trail_segment_count(), 0, "a run in progress draws a trail")
	# Every segment is a real edge between two real stars.
	for seg in view._trail:
		var a: int = int(seg[0])
		var b: int = int(seg[1])
		assert_true(a >= 0 and a < view.layout.star_count(), "trail start is a real star")
		assert_true(b >= 0 and b < view.layout.star_count(), "trail end is a real star")
		assert_true(view.neighbors_of(a).has(b), "a trail segment is a real connection")

func test_framing_the_trail_keeps_the_route_on_screen() -> void:
	var ui = OVERWORLD.instantiate()
	add_child_autofree(ui)
	ui.choose_start(0)
	var view := _open()
	if not view.has_layout() or view.trail_segment_count() == 0:
		return
	view.frame_trail()
	# The current game and the amulet both sit inside the framed view.
	var current: int = view.layout.index_of(GameState.current_game_id)
	var amulet: int = view.layout.index_of(GameState.amulet_game_id)
	var canvas := Rect2(Vector2.ZERO, view._canvas_size())
	for idx in [current, amulet]:
		if idx >= 0:
			assert_true(canvas.grow(4.0).has_point(view.to_screen(view.layout.position_of(idx))),
				"the route's endpoints are framed")
