var ENEMIES_DATA = [
  {
    "name": "Cultist",
    "powerLevel": "Low",
    "game": "Slay the Spire",
    "stat": "Charisma",
    "armorClass": 5,
    "health": 10,
    "attack": 1,
    "successReward": "Gain 5 Gold",
    "failureConsequence": "Low Curse",
    "imageUrl": "https://i.imgur.com/ajKKRcC.png"
  },
  {
    "name": "Snecko",
    "powerLevel": "Medium",
    "game": "Slay the Spire",
    "stat": "Charisma",
    "armorClass": 10,
    "health": 20,
    "attack": 2,
    "successReward": "Gain 10 Gold",
    "failureConsequence": "Medium Curse",
    "imageUrl": "https://i.imgur.com/RK1NDba.png"
  },
  {
    "name": "Transient",
    "powerLevel": "High",
    "game": "Slay the Spire",
    "stat": "Charisma",
    "armorClass": 15,
    "health": 30,
    "attack": 3,
    "successReward": "Gain 15 Gold",
    "failureConsequence": "High Curse",
    "imageUrl": "https://i.imgur.com/0cXmirR.png"
  },
  {
    "name": "Hobgoblin",
    "powerLevel": "Low",
    "game": "Rogue",
    "stat": "Dexterity",
    "armorClass": 5,
    "health": 10,
    "attack": 1,
    "successReward": "Gain 5 Gold",
    "failureConsequence": "Low Curse",
    "imageUrl": "https://i.imgur.com/A2PsbKv.png"
  },
  {
    "name": "Troll",
    "powerLevel": "Medium",
    "game": "Rogue",
    "stat": "Dexterity",
    "armorClass": 10,
    "health": 20,
    "attack": 2,
    "successReward": "Gain 10 Gold",
    "failureConsequence": "Medium Curse",
    "imageUrl": "https://i.imgur.com/UEmw7K9.png"
  },
  {
    "name": "Dragon",
    "powerLevel": "High",
    "game": "Rogue",
    "stat": "Dexterity",
    "armorClass": 15,
    "health": 30,
    "attack": 3,
    "successReward": "Gain 15 Gold",
    "failureConsequence": "High Curse",
    "imageUrl": "https://i.imgur.com/qyX0nMf.png"
  },
  {
    "name": "Mung",
    "powerLevel": "Low",
    "game": "Brutal Orchestra",
    "stat": "Intelligence",
    "armorClass": 5,
    "health": 10,
    "attack": 1,
    "successReward": "Gain 5 Gold",
    "failureConsequence": "Low Curse",
    "imageUrl": "https://i.imgur.com/kfbSTv7.png"
  },
  {
    "name": "Revola",
    "powerLevel": "Medium",
    "game": "Brutal Orchestra",
    "stat": "Intelligence",
    "armorClass": 10,
    "health": 20,
    "attack": 2,
    "successReward": "Gain 10 Gold",
    "failureConsequence": "Medium Curse",
    "imageUrl": "https://i.imgur.com/Db74QnA.png"
  },
  {
    "name": "Skinning Homunculus",
    "powerLevel": "High",
    "game": "Brutal Orchestra",
    "stat": "Intelligence",
    "armorClass": 15,
    "health": 30,
    "attack": 3,
    "successReward": "Gain 15 Gold",
    "failureConsequence": "High Curse",
    "imageUrl": "https://i.imgur.com/0ZzNMlg.png"
  },
  {
    "name": "Gaper",
    "powerLevel": "Low",
    "game": "The Binding of Isaac",
    "stat": "Strength",
    "armorClass": 5,
    "health": 10,
    "attack": 1,
    "successReward": "Gain 5 Gold",
    "failureConsequence": "Low Curse",
    "imageUrl": "https://i.imgur.com/GHYsk65.png"
  },
  {
    "name": "Double Vis",
    "powerLevel": "Medium",
    "game": "The Binding of Isaac",
    "stat": "Strength",
    "armorClass": 10,
    "health": 20,
    "attack": 2,
    "successReward": "Gain 10 Gold",
    "failureConsequence": "Medium Curse",
    "imageUrl": "https://i.imgur.com/LLdb6OR.png"
  },
  {
    "name": "Tainted Pooter",
    "powerLevel": "High",
    "game": "The Binding of Isaac",
    "stat": "Strength",
    "armorClass": 15,
    "health": 30,
    "attack": 3,
    "successReward": "Gain 15 Gold",
    "failureConsequence": "High Curse",
    "imageUrl": "https://i.imgur.com/IsLNEDt.png"
  },
  {
    "name": "Stone Golem",
    "powerLevel": "Medium",
    "game": "Risk of Rain",
    "stat": "Strength",
    "armorClass": 10,
    "health": 20,
    "attack": 2,
    "successReward": "Gain 10 Gold",
    "failureConsequence": "Medium Curse",
    "imageUrl": "https://imgur.com/AeB1zxt.png"
  },
];