// Auto-generated from Roguelikes.xlsx - Combat Statuses

var STATUSES_DATA = {
  "burn": {
    "name": "Burn",
    "description": "Deals 3 damage to any target per stack at the end of turn",
    "type": "Debuff",
    "stackable": true,
    "maxStack": null,
    "decay": "Down by 1 at end of turn",
    "who": "All",
    "preference": "Negative",
    "imageUrl": "images/statuses/Burn.png"
  },
  "poison": {
    "name": "Poison",
    "description": "Deals X damage to any target where X is the stack at the start of turn",
    "type": "Debuff",
    "stackable": true,
    "maxStack": null,
    "decay": "Down by 1 at end of turn",
    "who": "All",
    "preference": "Negative",
    "imageUrl": "images/statuses/Poison.png"
  },
  "dodge": {
    "name": "Dodge",
    "description": "Negate the next X sources of damage where X is the stack",
    "type": "Buff",
    "stackable": true,
    "maxStack": null,
    "decay": "Stack Goes down when player was going to lose health",
    "who": "All",
    "preference": "Positive",
    "imageUrl": "images/statuses/Dodge.png"
  },
  "power": {
    "name": "Power",
    "description": "Raise or Lower the damage dealth by this target by X",
    "type": "Buff",
    "stackable": true,
    "maxStack": null,
    "decay": "None",
    "who": "All",
    "preference": "Positive",
    "imageUrl": "images/statuses/Power.png"
  },
  "oiled": {
    "name": "Oiled",
    "description": "Burn deals double damage, and at end of turn, Dex save 10 or Lose 1 Energy",
    "type": "Debuff",
    "stackable": true,
    "maxStack": null,
    "decay": "Down by 1 at end of turn",
    "who": "All",
    "preference": "Negative",
    "imageUrl": "images/statuses/Oiled.png"
  },
  "forgetful": {
    "name": "Forgetful",
    "description": "Dice sides that have already been rolled cannot appear until all sides have been rolled",
    "type": "Ability",
    "stackable": false,
    "maxStack": 1,
    "decay": "Down by 1 when all sides have been rolled",
    "who": "All",
    "preference": "Negative",
    "imageUrl": "images/statuses/Forgetful.png"
  },
  "barricade": {
    "name": "Barricade",
    "description": "Block goes down by half at end of turn",
    "type": "Ability",
    "stackable": false,
    "maxStack": 1,
    "decay": "Down by 1 at end of turn",
    "who": "All",
    "preference": "Positive",
    "imageUrl": "images/statuses/Barricade.png"
  },
  "ruptured": {
    "name": "Ruptured",
    "description": "Deals 3 damage to the player when they use a dash to gain dodge",
    "type": "Debuff",
    "stackable": true,
    "maxStack": null,
    "decay": "Down by 1 when dash is used",
    "who": "All",
    "preference": "Negative",
    "imageUrl": "images/statuses/Ruptured.png"
  },
  "frail": {
    "name": "Frail",
    "description": "All damage deals double to target ",
    "type": "Debuff",
    "stackable": true,
    "maxStack": null,
    "decay": "Down by 1 at end of turn",
    "who": "All",
    "preference": "Negative",
    "imageUrl": "images/statuses/Frail.png"
  },
  "formless": {
    "name": "Formless",
    "description": "When dealt damage, change it's intent",
    "type": "Ability",
    "stackable": false,
    "maxStack": null,
    "decay": "None",
    "who": "Enemy",
    "preference": "Neutral",
    "imageUrl": "images/statuses/Formless.png"
  },
  "multi_attack_x": {
    "name": "Multi Attack X",
    "description": "This enemy has X amount of intents in a turn",
    "type": "Ability",
    "stackable": false,
    "maxStack": null,
    "decay": "None",
    "who": "Enemy",
    "preference": "Positive",
    "imageUrl": "images/statuses/MultiAttack.png"
  },
  "ritual": {
    "name": "Ritual",
    "description": "At the end of its turn, gains X Power",
    "type": "Buff",
    "stackable": true,
    "maxStack": null,
    "decay": "None",
    "who": "All",
    "preference": "Positive",
    "imageUrl": "images/statuses/Ritual.png"
  },
  "confused": {
    "name": "Confused",
    "description": "Each Dice Energy Cost is randomized between 0 and your max energy every roll",
    "type": "Debuff",
    "stackable": true,
    "maxStack": null,
    "decay": "Down by 1 at end of turn",
    "who": "Player",
    "preference": "Negative",
    "imageUrl": "images/statuses/Confused.png"
  },
  "fading_x": {
    "name": "Fading X",
    "description": "Dies in X turns",
    "type": "Debuff",
    "stackable": true,
    "maxStack": null,
    "decay": "Down by 1 at end of turn",
    "who": "All",
    "preference": "Negative",
    "imageUrl": "images/statuses/Fading.png"
  },
  "shifting": {
    "name": "Shifting",
    "description": "Loses X Power where X is the amount of damage taken this turn",
    "type": "Debuff",
    "stackable": false,
    "maxStack": null,
    "decay": "None",
    "who": "All",
    "preference": "Negative",
    "imageUrl": "images/statuses/Shifting.png"
  },
  "thorns": {
    "name": "Thorns",
    "description": "When a target with Thorns gets dealt or deals Melee Dmg, the target deals X Dmg to the attacker/recipient",
    "type": "Buff",
    "stackable": true,
    "maxStack": null,
    "decay": "None",
    "who": "All",
    "preference": "Positive",
    "imageUrl": "images/statuses/Thorns.png"
  },
  "vulnerable": {
    "name": "Vulnerable",
    "description": "All damage deals 50% more to target ",
    "type": "Debuff",
    "stackable": true,
    "maxStack": null,
    "decay": "Down by 1 at end of turn",
    "who": "All",
    "preference": "Negative",
    "imageUrl": "images/statuses/Vulnerable.png"
  },
  "weak": {
    "name": "Weak",
    "description": "Target deals 25% less damage.",
    "type": "Debuff",
    "stackable": true,
    "maxStack": null,
    "decay": "Down by 1 at end of turn",
    "who": "All",
    "preference": "Negative",
    "imageUrl": "images/statuses/Weak.png"
  },
  "stun": {
    "name": "Stun",
    "description": "The enemy's intent will be changed to \"Stunned\" and will do nothing on this turn ",
    "type": "Debuff",
    "stackable": false,
    "maxStack": 1,
    "decay": "Down by 1 at end of turn",
    "who": "Enemy",
    "preference": "Negative",
    "imageUrl": "images/statuses/Stun.png"
  },
  "unknown": {
    "name": "Unknown",
    "description": "This enemy intends to do something specific",
    "type": "Intent",
    "stackable": false,
    "maxStack": null,
    "decay": "None",
    "who": "Enemy",
    "preference": "Neutral",
    "imageUrl": "images/statuses/Unknown.png"
  },
  "stagger_x": {
    "name": "Stagger X",
    "description": "Target will gain Stun when hit with X% of Total Health lost in one hit",
    "type": "Ability",
    "stackable": false,
    "maxStack": null,
    "decay": "None",
    "who": "Enemy",
    "preference": "Negative",
    "imageUrl": "images/statuses/Stun.png"
  },
  "pigment_rich": {
    "name": "Pigment Rich",
    "description": "When hit, add a random pigment card to your hand.",
    "type": "Ability",
    "stackable": false,
    "maxStack": null,
    "decay": "None",
    "who": "Enemy",
    "preference": "Neutral",
    "imageUrl": "images/statuses/PigmentRich.png"
  },
  "rerollable": {
    "name": "Rerollable",
    "description": "Attacks from this enemy can be rerolled costing 1 Reroll",
    "type": "Ability",
    "stackable": false,
    "maxStack": null,
    "decay": "None",
    "who": "Enemy",
    "preference": "Neutral",
    "imageUrl": "images/statuses/Rerollable.png"
  },
  "rust": {
    "name": "Rust",
    "description": "If this enemy does damage that causes the player to lose health, Downgrade a random passive item",
    "type": "Ability",
    "stackable": false,
    "maxStack": null,
    "decay": "None",
    "who": "Enemy",
    "preference": "Neutral",
    "imageUrl": "images/statuses/Rust.png"
  },
  "brace": {
    "name": "Brace",
    "description": "Target takes 1 less damage from all sources per stack. (minimum 1)",
    "type": "Buff",
    "stackable": true,
    "maxStack": null,
    "decay": "None",
    "who": "All",
    "preference": "Positive",
    "imageUrl": "images/statuses/Brace.png",
    "rarity": "Common"
  },
  "bruise": {
    "name": "Bruise",
    "description": "Increases all melee and ranged damage taken by 1 per stack.",
    "type": "Debuff",
    "stackable": true,
    "maxStack": null,
    "decay": "None",
    "who": "All",
    "preference": "Negative",
    "imageUrl": "images/statuses/Bruise.png",
    "rarity": "Common"
  },
  "leeches": {
    "name": "Leeches",
    "description": "Drains 1 health per stack from all afflicted units at the end of the applier's turn and gives it to the applier. When hovering, it will say \"X's Leeches\"",
    "type": "Debuff",
    "stackable": true,
    "maxStack": null,
    "decay": "None",
    "who": "All",
    "preference": "Negative",
    "imageUrl": "images/statuses/Leeches.png",
    "rarity": "Uncommon"
  },
  "soul_link": {
    "name": "Soul Link",
    "description": "Whenever a soul linked target loses health, all soul linked characters lose that health as well.",
    "type": "Debuff",
    "stackable": false,
    "maxStack": null,
    "decay": "None",
    "who": "All",
    "preference": "Negative",
    "imageUrl": "images/statuses/SoulLink.png",
    "rarity": "Rare"
  },
  "holy_shield": {
    "name": "Holy Shield",
    "description": "The next time this unit gets hit, take no damage and lose 1 Holy Shield. This takes precedence over Block",
    "type": "Buff",
    "stackable": true,
    "maxStack": null,
    "decay": "When the target would take damage",
    "who": "All",
    "preference": "Positive",
    "imageUrl": "images/statuses/HolyShield.png",
    "rarity": "Rare"
  },
  "regeneration": {
    "name": "Regeneration",
    "description": "At the end of target's turn, it gains X health where X is the stack",
    "type": "Buff",
    "stackable": true,
    "maxStack": null,
    "decay": "Down by 1 at end of turn",
    "who": "All",
    "preference": "Positive",
    "imageUrl": "images/statuses/Regeneration.png",
    "rarity": "Uncommon"
  }
};
