// Auto-generated from Roguelikes.xlsx

var STATUSES_DATA = [
  {
    "name": "Burn",
    "description": "Deals 3 damage to any target per stack",
    "type": "Debuff",
    "stackable": true,
    "maxStack": null,
    "decay": "Down by 1 at end of turn",
    "who": "All",
    "preference": "Negative",
    "image": "images/statuses/Burn.png",
    "levelUp": "Common"
  },
  {
    "name": "Poison",
    "description": "Deals X damage to any target where X is the stack ",
    "type": "Debuff",
    "stackable": true,
    "maxStack": null,
    "decay": "Down by 1 at end of turn",
    "who": "All",
    "preference": "Negative",
    "image": "images/statuses/Poison.png",
    "levelUp": "Common"
  },
  {
    "name": "Dodge",
    "description": "Negate the next X sources of damage where X is the stack",
    "type": "Buff",
    "stackable": true,
    "maxStack": null,
    "decay": "Stack Goes down when hit",
    "who": "All",
    "preference": "Positive",
    "image": "images/statuses/Dodge.png",
    "levelUp": "Rare"
  },
  {
    "name": "Power",
    "description": "Raise or Lower the damage dealth by this target by X",
    "type": "Buff",
    "stackable": true,
    "maxStack": null,
    "decay": "None",
    "who": "All",
    "preference": "Positive",
    "image": "images/statuses/Power.png",
    "levelUp": "Uncommon"
  },
  {
    "name": "Oiled",
    "description": "Burn deals double damage, and at end of turn, Dex save 10 or Lose 1 Energy",
    "type": "Debuff",
    "stackable": true,
    "maxStack": null,
    "decay": "Down by 1 at end of turn",
    "who": "All",
    "preference": "Negative",
    "image": "images/statuses/Oiled.png",
    "levelUp": "N/A"
  },
  {
    "name": "Forgetful",
    "description": "Dice sides that have already been rolled cannot appear until all sides have been rolled",
    "type": "Ability",
    "stackable": false,
    "maxStack": 1,
    "decay": "Down by 1 when all sides have been rolled",
    "who": "All",
    "preference": "Negative",
    "image": "images/statuses/Forgetful.png",
    "levelUp": "N/A"
  },
  {
    "name": "Barricade",
    "description": "Block goes down by half at end of turn",
    "type": "Ability",
    "stackable": false,
    "maxStack": 1,
    "decay": "Down by 1 at end of turn",
    "who": "All",
    "preference": "Positive",
    "image": "images/statuses/Barricade.png",
    "levelUp": "Rare"
  },
  {
    "name": "Ruptured",
    "description": "Deals 3 damage to the player when they dodge",
    "type": "Debuff",
    "stackable": true,
    "maxStack": null,
    "decay": "Down by 1 when dash is used",
    "who": "All",
    "preference": "Negative",
    "image": "images/statuses/Ruptured.png",
    "levelUp": "N/A"
  },
  {
    "name": "Frail",
    "description": "All damage to target is doubled",
    "type": "Debuff",
    "stackable": true,
    "maxStack": null,
    "decay": "Down by 1 at end of turn",
    "who": "All",
    "preference": "Negative",
    "image": "images/statuses/Frail.png",
    "levelUp": "Rare"
  },
  {
    "name": "Formless",
    "description": "When dealth damage, reroll's their intent die",
    "type": "Ability",
    "stackable": false,
    "maxStack": null,
    "decay": "None",
    "who": "Enemy",
    "preference": "Neutral",
    "image": "images/statuses/Formless.png",
    "levelUp": "N/A"
  },
  {
    "name": "Multi Attack X",
    "description": "This enemy rolls X amount of die at a time",
    "type": "Ability",
    "stackable": false,
    "maxStack": null,
    "decay": "None",
    "who": "Enemy",
    "preference": "Positive",
    "image": "images/statuses/MultiAttack.png",
    "levelUp": "N/A"
  },
  {
    "name": "Ritual",
    "description": "At the end of its turn, gains X Power",
    "type": "Buff",
    "stackable": true,
    "maxStack": null,
    "decay": "None",
    "who": "All",
    "preference": "Positive",
    "image": "images/statuses/Ritual.png",
    "levelUp": "Rare"
  },
  {
    "name": "Confused",
    "description": "Each Dice Energy Cost is randomized between 0 and your max energy every roll",
    "type": "Debuff",
    "stackable": true,
    "maxStack": null,
    "decay": "Down by 1 at end of turn",
    "who": "Player",
    "preference": "Negative",
    "image": "images/statuses/Confused.png",
    "levelUp": "N/A"
  },
  {
    "name": "Fading X",
    "description": "Dies in X turns",
    "type": "Debuff",
    "stackable": true,
    "maxStack": null,
    "decay": "Down by 1 at end of turn",
    "who": "All",
    "preference": "Negative",
    "image": "images/statuses/Fading.png",
    "levelUp": "N/A"
  },
  {
    "name": "Shifting",
    "description": "Loses X Power where X is the amount of damage taken this turn",
    "type": "Debuff",
    "stackable": false,
    "maxStack": null,
    "decay": "None",
    "who": "All",
    "preference": "Negative",
    "image": "images/statuses/Shifting.png",
    "levelUp": "N/A"
  },
  {
    "name": "Thorns",
    "description": "When a target with Thorns gets dealt Dmg directly, the attacker takes X Dmg",
    "type": "Buff",
    "stackable": true,
    "maxStack": null,
    "decay": "None",
    "who": "All",
    "preference": "Positive",
    "image": "images/statuses/Thorns.png",
    "levelUp": "Uncommon"
  }
];
