class_name AtlasLayout
extends Resource

# Baked star positions for the Atlas screen — the whole 751-game influence graph
# laid out as constellations around the highest-degree hubs.
#
# Generated by `tools/bake_atlas.py`, which is a pure function of
# `data/games/*.tres`. Re-run it after `import-games-godot.py` and the sky
# updates with the catalog; nothing here is computed at runtime, so a game's
# position is identical in every session and on every machine.
#
# Every array below is indexed the same way — index i refers to `game_ids[i]` —
# so a lookup is one Dictionary hit (see `index_of`) followed by array reads.

# Which Settings.game_filter this sky was baked for: "all", "owned" or
# "downloaded". Each is laid out over its own subgraph, so an owned-only sky has
# its own capitals rather than being the full map with stars hidden.
@export var source_filter: String = "all"

# Canonical game ids, sorted, one per star.
@export var game_ids: PackedStringArray = PackedStringArray()

# Star position in layout space. Not pixels — the view scales to fit.
@export var xs: PackedFloat32Array = PackedFloat32Array()
@export var ys: PackedFloat32Array = PackedFloat32Array()

# Which constellation a game belongs to, as an index into `capitals`.
# -1 means no capital can reach it — a drifting star.
@export var region: PackedInt32Array = PackedInt32Array()

# Hops from the game to its region's capital. -1 for drifting stars.
@export var hops: PackedInt32Array = PackedInt32Array()

# Undirected edges as flat index pairs: edges[0]-edges[1], edges[2]-edges[3], …
# Deduped, and holding only edges BETWEEN stars in this layout: a sky is a whole
# graph, not a graph with some of it hidden. A baked sky covers whatever
# Settings.game_filter selected; a runtime one (AtlasLayoutBuilder) covers
# whatever the Collection's filters left standing.
@export var edges: PackedInt32Array = PackedInt32Array()

# Star indices of the capitals, in descending degree order.
@export var capitals: PackedInt32Array = PackedInt32Array()

# TREE SKIES ONLY: each star's parent in the tree being drawn, -1 for the root
# and for anything the tree doesn't reach (the unconnected outer ring). Empty on
# a constellation sky, which has no single tree — `is_tree()` is that test.
#
# It exists because a tree drawn with all 1,115 links at equal weight is a
# hairball: the branch a game hangs off is the thing the layout is *for*, so the
# view draws those links solid and everything else as faint cross-talk.
@export var parent: PackedInt32Array = PackedInt32Array()

# Where each constellation sits and how far it reaches, one entry per capital.
# The packer built each cluster around its capital and knows these exactly, so
# the view never derives them from a centroid — that lands off-centre on a
# lopsided region and drags the name label with it.
@export var region_cx: PackedFloat32Array = PackedFloat32Array()
@export var region_cy: PackedFloat32Array = PackedFloat32Array()
@export var region_radius: PackedFloat32Array = PackedFloat32Array()

# Bounding box of every star, with a little margin. Used to frame the view.
@export var bounds: Rect2 = Rect2()

var _index: Dictionary = {}        # StringName -> int
var _degree: PackedInt32Array = PackedInt32Array()

func _build_cache() -> void:
	if not _index.is_empty() or game_ids.is_empty():
		return
	for i in range(game_ids.size()):
		_index[StringName(game_ids[i])] = i
	_degree.resize(game_ids.size())
	_degree.fill(0)
	var i := 0
	while i + 1 < edges.size():
		_degree[edges[i]] += 1
		_degree[edges[i + 1]] += 1
		i += 2

# Star index for a game id, or -1 if the layout predates that game (re-bake).
func index_of(game_id: StringName) -> int:
	_build_cache()
	return int(_index.get(game_id, -1))

func star_count() -> int:
	return game_ids.size()

func edge_count() -> int:
	return edges.size() / 2

func position_of(i: int) -> Vector2:
	return Vector2(xs[i], ys[i])

func id_at(i: int) -> StringName:
	return StringName(game_ids[i])

# How many connections a star has. Read off the baked edge list rather than
# RunGraph, so it matches what the atlas actually draws.
func degree_of(i: int) -> int:
	_build_cache()
	return _degree[i]

# Drawn radius of a star. Must match `star_radius()` in tools/bake_atlas.py —
# the packing guarantees no two stars overlap at these radii.
static func star_radius(degree: int) -> float:
	return 1.5 + sqrt(float(degree)) * 0.95

func is_capital(i: int) -> bool:
	return capitals.has(i)

# Whether this sky is a tree (one root, every star hanging off a parent) rather
# than a set of constellations.
func is_tree() -> bool:
	return not parent.is_empty()

# Whether the link between stars `a` and `b` is one of the tree's own branches.
# False on a constellation sky, where there is no tree to be part of.
func is_tree_edge(a: int, b: int) -> bool:
	if parent.is_empty():
		return false
	return parent[a] == b or parent[b] == a

# Display name of the capital a star belongs to, or "" when it drifts.
func region_name(i: int) -> String:
	var r: int = region[i]
	if r < 0 or r >= capitals.size():
		return ""
	var game: GameData = Data.get_game(id_at(capitals[r]))
	return game.display_name if game != null else String(id_at(capitals[r]))
