class_name StatusData
extends Resource

# Static definition of a STATUS — the games-first redesign's balance lever
# (docs/games-first-redesign.md §13). A status is not a stat modifier and it is
# not combat state: it is a CLAUSE bolted onto the run's goals, which is the only
# currency this game has. Everything a status can do is one of four rearrangements
# of the same two authored pieces (`condition` + `reward`):
#
#   BUFF on the PLAYER    an extra standing goal — "If <condition>, gain <reward>"
#                         — that shows up on the goal list and pays out every game
#                         you satisfy it.
#   BUFF on an ENEMY      that enemy's goal gains "and <condition>". REQUIRED: the
#                         goal isn't met until you did both.
#   DEBUFF on the PLAYER  every enemy's goal gains "and <condition>", and the stack
#                         ticks down by 1 each game you complete it.
#   DEBUFF on an ENEMY    that enemy gains an OPTIONAL bonus row — "and if
#                         <condition>, gain <reward>" — claimable alongside its goal.
#
# So a buff pays the player and taxes the enemy's goal; a debuff taxes the player's
# goals and pays out on the enemy. That symmetry is the whole system, and it is why
# a location, an item, or a scroll can reach into the run's difficulty without any
# of them knowing what a goal is.
#
# Source-of-truth content lives in the `statuses2.0` sheet of
# tools/Roguelikes.xlsx and is generated into data/statuses2.0/*.tres by
# tools/generate_status_tres.py.

@export var id: StringName
@export var display_name: String

# Buff or Debuff (the sheet's Type column), lowercased. Decides which of the four
# quadrants above a given application lands in — together with who it was applied
# to, that is the entire dispatch.
@export var kind: StringName = &"buff"

# The real roguelike the status is lifted from (Slay the Spire, Mewgenics).
# Informational / flavour, same role as GoalEnemyData.source_game.
@export var source_game: String = ""

# The sheet's prose for each quadrant, kept verbatim for tooltips and the
# collection screen. The ENGINE never parses these — it builds its own wording
# from `condition` / `reward` — but they are the author's intent, so a mismatch
# between the prose and the generated text is a content bug worth being able to
# see. Not the display path: use player_goal_text / enemy_clause / bonus_text.
@export var on_player_text: String = ""
@export var on_enemy_text: String = ""

# How the sheet says stacks combine ("Intensity" for the current roster — a second
# application raises X rather than starting a second timer). Kept as text because
# nothing else has been authored yet; `stacks_by_intensity()` is the question the
# code actually asks.
@export var stackable: String = "Intensity"

# The challenge clause, with `{expr}` holes evaluated against the stack count X
# (see `resolve`). "you get {X} achievements" / "beaten in {1+pow(0.5,X-2)} hours
# or less". This is the ONE piece of text every quadrant is built out of.
@export var condition: String = ""

# What completing the condition pays, as EffectSystem effect dicts with `{expr}`
# holes preserved in a parallel `scaled` map (see `reward_effects`). Empty for a
# status that only taxes.
@export var reward: Array = []

# Human-readable reward wording, generated by the sheet generator from `reward`
# so the checklist can show "+2 Small Chests, +2 Bash" without re-deriving it.
@export var reward_text: String = ""

# Whether a stack falls off when its condition is completed. Buffs persist for the
# run (they ARE the reward); debuffs tick down, which is what makes them survivable
# — Marked's sheet cell says so outright.
@export var decays_on_complete: bool = false

# Art base name under res://images2.0/statuses/ (the sheet's Image column).
@export var file: String = ""
@export var image: Texture2D

# --- kind -----------------------------------------------------------------

func is_buff() -> bool:
	return kind == &"buff"

func is_debuff() -> bool:
	return kind == &"debuff"

# True when a second application raises X instead of stacking independently — the
# only mode the current roster authors, but asked as a question so a future
# "Duration" status doesn't have to be special-cased at every call site.
func stacks_by_intensity() -> bool:
	return stackable.to_lower().begins_with("intensity")

func art_file() -> String:
	return file if file != "" else display_name.replace(" ", "").replace("'", "")

# --- text -----------------------------------------------------------------

# The condition clause at `stacks`, with every `{expr}` hole evaluated:
#   Marked 3    -> "you get 3 achievements"
#   Dexterity 3 -> "beaten in 1.5 hours or less"
func condition_text(stacks: int) -> String:
	return resolve(condition, stacks)

# The reward wording at `stacks` — "+2 Small Chests, +2 Bash".
func reward_at(stacks: int) -> String:
	return resolve(reward_text, stacks)

# BUFF ON PLAYER — the extra goal row. The reward is part of the line because the
# whole point of the row is that it pays; a goal you might skip has to advertise
# what skipping costs you.
func player_goal_text(stacks: int) -> String:
	var line: String = "If %s" % condition_text(stacks)
	var pay: String = reward_at(stacks)
	if pay != "":
		line += ", gain %s" % pay
	return line

# BUFF ON ENEMY / DEBUFF ON PLAYER — the clause ANDed onto a goal. Rendered
# without the leading "and" so the caller can join it however its line reads.
func enemy_clause(stacks: int) -> String:
	return condition_text(stacks)

# DEBUFF ON ENEMY — the optional bonus row hanging off that enemy's goal.
func bonus_text(stacks: int) -> String:
	var line: String = "and if %s" % condition_text(stacks)
	var pay: String = reward_at(stacks)
	if pay != "":
		line += ", gain %s" % pay
	return line

# --- reward effects -------------------------------------------------------

# The reward as EffectSystem-ready effect dicts at `stacks`. The generator stores
# each effect with its `{expr}` holes listed in a `scaled` sub-dict (field name ->
# expression); this evaluates them at X = stacks and returns plain dicts the
# EffectSystem can apply unchanged:
#
#   {"type": "gain_chest", "choices": 1, "scaled": {"value": "X"}}   at X=2
#     -> {"type": "gain_chest", "choices": 1, "value": 2}
func reward_effects(stacks: int) -> Array:
	var out: Array = []
	for raw in reward:
		if not (raw is Dictionary):
			continue
		var eff: Dictionary = (raw as Dictionary).duplicate(true)
		var scaled: Dictionary = eff.get("scaled", {})
		eff.erase("scaled")
		for field in scaled.keys():
			eff[field] = int(round(evaluate(String(scaled[field]), stacks)))
		out.append(eff)
	return out

# --- the {expr} mini-language --------------------------------------------

# Substitutes every hole in `text` at X = `stacks`. Two kinds:
#
#   {expr}              an arithmetic expression over X, formatted for reading:
#                       whole numbers lose their decimal tail ("2", not "2.0") and
#                       fractional ones keep only the digits they need ("1.5").
#   [singular|plural]   agrees in number with the {expr} most recently resolved,
#                       so "+{X} [Small Chest|Small Chests]" reads correctly at
#                       every stack count instead of picking one and being wrong
#                       at the other. Before any number has been seen it takes the
#                       plural, which is the reading a bare noun wants.
func resolve(text: String, stacks: int) -> String:
	if text == "" or not (text.contains("{") or text.contains("[")):
		return text
	var out: String = ""
	var rest: String = text
	var last_value: float = INF   # nothing counted yet
	while true:
		var open_at: int = _first_hole(rest)
		if open_at < 0:
			out += rest
			break
		var is_expr: bool = rest[open_at] == "{"
		var close_at: int = rest.find("}" if is_expr else "]", open_at)
		if close_at < 0:
			out += rest
			break
		out += rest.substr(0, open_at)
		var body: String = rest.substr(open_at + 1, close_at - open_at - 1)
		if is_expr:
			last_value = evaluate(body, stacks)
			out += format_number(last_value)
		else:
			var forms: PackedStringArray = body.split("|")
			var singular: bool = forms.size() > 1 and is_equal_approx(last_value, 1.0)
			out += forms[0] if singular else forms[forms.size() - 1]
		rest = rest.substr(close_at + 1)
	return out

# The first `{` or `[` in `text`, whichever comes first; -1 when neither is there.
func _first_hole(text: String) -> int:
	var brace: int = text.find("{")
	var bracket: int = text.find("[")
	if brace < 0:
		return bracket
	if bracket < 0:
		return brace
	return mini(brace, bracket)

# One arithmetic expression over X, via Godot's own Expression parser — so a status
# can scale on whatever curve the sheet feels like without the engine knowing the
# shapes in advance. The generator has already rewritten the sheet's `a^b` into
# `pow(a, b)`. A malformed expression warns and reads as the raw stack count rather
# than taking the run down.
func evaluate(expr: String, stacks: int) -> float:
	var e := Expression.new()
	if e.parse(expr.strip_edges(), ["X"]) != OK:
		push_warning("StatusData %s: cannot parse '%s' (%s)" % [id, expr, e.get_error_text()])
		return float(stacks)
	var value: Variant = e.execute([stacks], null, false)
	if e.has_execute_failed():
		push_warning("StatusData %s: cannot evaluate '%s'" % [id, expr])
		return float(stacks)
	if value is float or value is int:
		return float(value)
	return float(stacks)

# 2.0 -> "2", 1.5 -> "1.5", 1.125 -> "1.125". Trailing zeros are noise on a
# checklist row, and "beaten in 2.000000 hours" reads as a bug.
static func format_number(v: float) -> String:
	if is_equal_approx(v, round(v)):
		return str(int(round(v)))
	var s: String = "%.4f" % v
	while s.ends_with("0"):
		s = s.substr(0, s.length() - 1)
	if s.ends_with("."):
		s = s.substr(0, s.length() - 1)
	return s
